// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

// Package extensions implements the 𝔽r³ extension of the mamabear field.
//
//   - For extension 3:
//     𝔽r³[t] = 𝔽r/t³-t-1
package extensions
