// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package extensions

import (
	"unsafe"

	fr "github.com/consensys/gnark-crypto/field/mamabear"
	"github.com/consensys/gnark-crypto/utils/cpu"
)

// Butterfly sets a = a+b and b = a-b (mod p) for each component.
func Butterfly(a, b *E3) {
	t := *a
	a.Add(a, b)
	b.Sub(&t, b)
}

// Vector is a slice of E3 elements.
type Vector []E3

// Butterfly computes the in-place butterfly between two same-length vectors:
//
//	vector[i] = vector[i] + other[i]
//	other[i]  = old vector[i] - other[i]
func (vector Vector) Butterfly(other Vector) {
	if len(vector) != len(other) {
		panic("vector.Butterfly: length mismatch")
	}
	for i := range vector {
		Butterfly(&vector[i], &other[i])
	}
}

// ButterflyPair applies Butterfly to each adjacent pair in the vector:
// (vector[0], vector[1]), (vector[2], vector[3]), ...
// Length must be even.
func (vector Vector) ButterflyPair() {
	if len(vector)%2 != 0 {
		panic("vector.ButterflyPair: length must be even")
	}
	for i := 0; i < len(vector); i += 2 {
		Butterfly(&vector[i], &vector[i+1])
	}
}

// MulByElement sets vector[i] = a[i] * b[i] where b[i] ∈ F_p.
func (vector Vector) MulByElement(a Vector, b fr.Vector) {
	if len(vector) != len(a) || len(vector) != len(b) {
		panic("vector.MulByElement: length mismatch")
	}
	for i := range vector {
		vector[i].MulByElement(&a[i], &b[i])
	}
}

// ScalarMulByElement sets vector[i] = a[i] * b for all i, where b ∈ F_p.
//
// Reinterprets the E3 slice as a flat fr.Vector (3 contiguous fr.Elements per E3)
// to leverage the optimized fr.Vector.ScalarMul path.
func (vector Vector) ScalarMulByElement(a Vector, b *fr.Element) {
	if len(vector) != len(a) {
		panic("vector.ScalarMulByElement: length mismatch")
	}
	if len(vector) == 0 {
		return
	}
	// E3 = {A0, A1, A2} with no padding — safe to reinterpret as 3×fr.Element.
	M := len(a) * 3
	vBase := fr.Vector(unsafe.Slice((*fr.Element)(unsafe.Pointer(&a[0])), M))
	vRes := fr.Vector(unsafe.Slice((*fr.Element)(unsafe.Pointer(&vector[0])), M))
	vRes.ScalarMul(vBase, b)
}

// ScalarMul sets vector[i] = a[i] * b for all i, where b ∈ E3.
func (vector Vector) ScalarMul(a Vector, b *E3) {
	if len(vector) != len(a) {
		panic("vector.ScalarMul: length mismatch")
	}
	for i := range vector {
		vector[i].Mul(&a[i], b)
	}
}

// InnerProduct returns ∑ vector[i] * a[i] over E3.
func (vector Vector) InnerProduct(a Vector) E3 {
	if len(vector) != len(a) {
		panic("vector.InnerProduct: vectors don't have the same length")
	}
	var res, tmp E3
	for i := range vector {
		tmp.Mul(&vector[i], &a[i])
		res.Add(&res, &tmp)
	}
	return res
}

// InnerProductByElement returns ∑ vector[i] * a[i] where a[i] ∈ F_p.
func (vector Vector) InnerProductByElement(a fr.Vector) E3 {
	if len(vector) != len(a) {
		panic("vector.InnerProductByElement: vectors don't have the same length")
	}
	var res, tmp E3
	for i := range vector {
		tmp.MulByElement(&vector[i], &a[i])
		res.Add(&res, &tmp)
	}
	return res
}

// mulAccByElementThreshold is the minimum vector length above which
// MulAccByElement batches through fr.Vector's Mul/Add kernels. Below it, the
// tiling overhead outweighs the win even when those kernels are accelerated.
const mulAccByElementThreshold = 64

// MulAccByElement adds scale[i] * alpha to vector[i] for all i.
//
// On AVX-512IFMA hardware, and for large enough vectors, the interleaved E3
// layout (A0, A1, A2 per element) is reinterpreted as a flat fr.Vector and
// processed with fr.Vector's Mul/Add, which dispatch to the AVX-512IFMA
// kernels. Without AVX-512IFMA, fr.Vector.Mul/Add fall back to the same
// per-element scalar loop this batching wraps around, so the extra tiling
// work is pure overhead — in that case we use the plain scalar loop instead.
func (vector Vector) MulAccByElement(scale []fr.Element, alpha *E3) {
	n := len(vector)
	if n != len(scale) {
		panic("vector.MulAccByElement: length mismatch")
	}
	if n == 0 {
		return
	}
	if !cpu.SupportAVX512IFMA || n < mulAccByElementThreshold {
		mulAccByElementGeneric(vector, scale, alpha)
		return
	}
	mulAccByElementBatched(vector, scale, alpha)
}

// mulAccByElementBatched implements MulAccByElement by reinterpreting the
// interleaved E3 layout (A0, A1, A2 per element) as a flat fr.Vector and
// processing it with fr.Vector's Mul/Add, which dispatch to the AVX-512IFMA
// kernels on amd64. Split out from MulAccByElement so its correctness can be
// tested independently of cpu.SupportAVX512IFMA.
func mulAccByElementBatched(vector Vector, scale []fr.Element, alpha *E3) {
	n := len(vector)

	// E3 = {A0, A1, A2} with no padding — safe to reinterpret as 3×fr.Element.
	M := n * 3
	flatVector := fr.Vector(unsafe.Slice((*fr.Element)(unsafe.Pointer(&vector[0])), M))

	tiledScale := make(fr.Vector, M)
	tiledAlpha := make(fr.Vector, M)
	for i := range scale {
		tiledScale[3*i] = scale[i]
		tiledScale[3*i+1] = scale[i]
		tiledScale[3*i+2] = scale[i]
		tiledAlpha[3*i] = alpha.A0
		tiledAlpha[3*i+1] = alpha.A1
		tiledAlpha[3*i+2] = alpha.A2
	}

	tmp := make(fr.Vector, M)
	tmp.Mul(tiledScale, tiledAlpha)
	flatVector.Add(flatVector, tmp)
}

func mulAccByElementGeneric(vector Vector, scale []fr.Element, alpha *E3) {
	var tmp E3
	for i := range vector {
		tmp.MulByElement(alpha, &scale[i])
		vector[i].Add(&vector[i], &tmp)
	}
}
