// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package extensions

import (
	"testing"

	fr "github.com/consensys/gnark-crypto/field/mamabear"
)

// TestMulAccByElementBatchedMatchesGeneric verifies the batched tiling
// implementation independently of cpu.SupportAVX512IFMA, since on hardware
// without AVX-512IFMA (e.g. arm64), MulAccByElement's dispatch never
// exercises mulAccByElementBatched.
func TestMulAccByElementBatchedMatchesGeneric(t *testing.T) {
	for _, n := range []int{1, 7, 8, 64, 65, 100, 1000} {
		dst := make(Vector, n)
		scale := make([]fr.Element, n)
		for i := range n {
			dst[i].MustSetRandom()
			scale[i].MustSetRandom()
		}
		var alpha E3
		alpha.MustSetRandom()

		expected := make(Vector, n)
		copy(expected, dst)
		mulAccByElementGeneric(expected, scale, &alpha)

		got := make(Vector, n)
		copy(got, dst)
		mulAccByElementBatched(got, scale, &alpha)

		for i := range n {
			if !got[i].Equal(&expected[i]) {
				t.Fatalf("n=%d: mulAccByElementBatched[%d] mismatch with generic", n, i)
			}
		}
	}
}
