// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package polynomial

import (
	"github.com/consensys/gnark-crypto/ecc/bls24-317/fr"
	"github.com/consensys/gnark-crypto/utils"
)

// Pool is a pool of slices of fr.Element
type Pool = utils.Pool[fr.Element]

// NewPool returns a Pool whose sub-pools hold slices of capacity up to each of maxN
func NewPool(maxN ...int) Pool {
	return utils.NewPool[fr.Element](maxN...)
}
