// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package fflonk

import (
	"bytes"
	"crypto/sha256"
	"math/big"
	"testing"

	"github.com/consensys/gnark-crypto/ecc"
	bls24315 "github.com/consensys/gnark-crypto/ecc/bls24-315"
	"github.com/consensys/gnark-crypto/ecc/bls24-315/fr"
	"github.com/consensys/gnark-crypto/ecc/bls24-315/kzg"
	"github.com/consensys/gnark-crypto/utils/testutils"
	"github.com/stretchr/testify/require"
)

// Test SRS re-used across tests of the KZG scheme
var testSrs *kzg.SRS
var bAlpha *big.Int

func init() {
	const srsSize = 600
	bAlpha = new(big.Int).SetInt64(42) // randomise ?
	testSrs, _ = kzg.NewSRS(ecc.NextPowerOfTwo(srsSize), bAlpha)
}

func TestSerialization(t *testing.T) {

	_, _, g, _ := bls24315.Generators()
	var proof OpeningProof
	proof.SOpeningProof.W.Set(&g)
	proof.SOpeningProof.WPrime.Set(&g)
	proof.SOpeningProof.ClaimedValues = make([][]fr.Element, 3)
	for i := range proof.SOpeningProof.ClaimedValues {
		proof.SOpeningProof.ClaimedValues[i] = make([]fr.Element, i+2)
		for j := range proof.SOpeningProof.ClaimedValues[i] {
			proof.SOpeningProof.ClaimedValues[i][j].MustSetRandom()
		}
	}
	proof.ClaimedValues = make([][][]fr.Element, 2)
	for i := range proof.ClaimedValues {
		proof.ClaimedValues[i] = make([][]fr.Element, 3)
		for j := range proof.ClaimedValues[i] {
			proof.ClaimedValues[i][j] = make([]fr.Element, i+j+1)
			for k := range proof.ClaimedValues[i][j] {
				proof.ClaimedValues[i][j][k].MustSetRandom()
			}
		}
	}

	t.Run("opening proof round trip", testutils.SerializationRoundTrip(&proof))
	t.Run("opening proof raw round trip", testutils.SerializationRoundTripRaw(&proof))
	t.Run("opening proof unsafe raw round trip", func(t *testing.T) {
		var buf bytes.Buffer
		_, err := proof.WriteRawTo(&buf)
		require.NoError(t, err)

		var reconstructed OpeningProof
		_, err = reconstructed.UnsafeReadFrom(&buf)
		require.NoError(t, err)
		require.Equal(t, proof, reconstructed)
	})
}

func TestFflonk(t *testing.T) {

	assert := require.New(t)

	// sample random polynomials of various sizes
	nbSets := 5
	p := make([][][]fr.Element, nbSets)
	for i := range nbSets {
		nbPolysInSet := 9
		p[i] = make([][]fr.Element, nbPolysInSet)
		for j := range nbPolysInSet {
			curSizePoly := j + 10
			p[i][j] = make([]fr.Element, curSizePoly)
			for k := range curSizePoly {
				p[i][j][k].MustSetRandom()
			}
		}
	}

	// sample random sets Sᵢ
	x := make([][]fr.Element, nbSets)
	for i := range nbSets {
		curSetSize := i + 4
		x[i] = make([]fr.Element, curSetSize)
		for j := range curSetSize {
			x[i][j].MustSetRandom()
		}
	}

	// commit to the folded polynomials
	digests := make([]kzg.Digest, nbSets)
	var err error
	for i := range nbSets {
		digests[i], err = FoldAndCommit(p[i], testSrs.Pk)
		assert.NoError(err)
	}

	// compute flonk opening proof
	hf := sha256.New()
	proof, err := BatchOpen(p, digests, x, hf, testSrs.Pk)
	assert.NoError(err)

	// check opening proof
	err = BatchVerify(proof, digests, x, hf, testSrs.Vk)
	assert.NoError(err)

	// tamper the proof
	proof.ClaimedValues[0][0][0].MustSetRandom()
	err = BatchVerify(proof, digests, x, hf, testSrs.Vk)
	assert.Error(err)

}

// TestBatchVerifyMalformedShape checks that BatchVerify rejects proofs whose
// dimensions are inconsistent instead of panicking with an index out of range.
// All of these shapes are reachable from deserialised, attacker supplied data.
func TestBatchVerifyMalformedShape(t *testing.T) {

	assert := require.New(t)

	// build one valid proof, then deform it in various ways
	nbSets := 3
	p := make([][][]fr.Element, nbSets)
	for i := range nbSets {
		nbPolysInSet := 4
		p[i] = make([][]fr.Element, nbPolysInSet)
		for j := range nbPolysInSet {
			curSizePoly := j + 10
			p[i][j] = make([]fr.Element, curSizePoly)
			for k := range curSizePoly {
				p[i][j][k].MustSetRandom()
			}
		}
	}

	x := make([][]fr.Element, nbSets)
	for i := range nbSets {
		curSetSize := i + 4
		x[i] = make([]fr.Element, curSetSize)
		for j := range curSetSize {
			x[i][j].MustSetRandom()
		}
	}

	digests := make([]kzg.Digest, nbSets)
	var err error
	for i := range nbSets {
		digests[i], err = FoldAndCommit(p[i], testSrs.Pk)
		assert.NoError(err)
	}

	hf := sha256.New()
	validProof, err := BatchOpen(p, digests, x, hf, testSrs.Pk)
	assert.NoError(err)
	assert.NoError(BatchVerify(validProof, digests, x, hf, testSrs.Vk))

	// deep copy so that each subtest starts from the valid proof
	cloneProof := func() OpeningProof {
		var c OpeningProof
		c.SOpeningProof.W = validProof.SOpeningProof.W
		c.SOpeningProof.WPrime = validProof.SOpeningProof.WPrime
		c.SOpeningProof.ClaimedValues = make([][]fr.Element, len(validProof.SOpeningProof.ClaimedValues))
		for i := range c.SOpeningProof.ClaimedValues {
			c.SOpeningProof.ClaimedValues[i] = append([]fr.Element{}, validProof.SOpeningProof.ClaimedValues[i]...)
		}
		c.ClaimedValues = make([][][]fr.Element, len(validProof.ClaimedValues))
		for i := range c.ClaimedValues {
			c.ClaimedValues[i] = make([][]fr.Element, len(validProof.ClaimedValues[i]))
			for j := range c.ClaimedValues[i] {
				c.ClaimedValues[i][j] = append([]fr.Element{}, validProof.ClaimedValues[i][j]...)
			}
		}
		return c
	}
	clonePoints := func() [][]fr.Element {
		c := make([][]fr.Element, len(x))
		for i := range x {
			c[i] = append([]fr.Element{}, x[i]...)
		}
		return c
	}

	testCases := []struct {
		name   string
		deform func(proof *OpeningProof, digests *[]kzg.Digest, points *[][]fr.Element)
	}{
		{
			name: "empty pack in ClaimedValues",
			deform: func(proof *OpeningProof, _ *[]kzg.Digest, _ *[][]fr.Element) {
				proof.ClaimedValues[0] = nil
			},
		},
		{
			name: "SOpeningProof.ClaimedValues shorter than ClaimedValues",
			deform: func(proof *OpeningProof, _ *[]kzg.Digest, _ *[][]fr.Element) {
				proof.SOpeningProof.ClaimedValues = proof.SOpeningProof.ClaimedValues[:len(proof.SOpeningProof.ClaimedValues)-1]
			},
		},
		{
			name: "points row shorter than the claimed row",
			deform: func(_ *OpeningProof, _ *[]kzg.Digest, points *[][]fr.Element) {
				(*points)[0] = (*points)[0][:len((*points)[0])-1]
			},
		},
		{
			name: "points longer than ClaimedValues",
			deform: func(proof *OpeningProof, _ *[]kzg.Digest, _ *[][]fr.Element) {
				proof.ClaimedValues = proof.ClaimedValues[:len(proof.ClaimedValues)-1]
			},
		},
		{
			name: "digests shorter than points",
			deform: func(_ *OpeningProof, digests *[]kzg.Digest, _ *[][]fr.Element) {
				*digests = (*digests)[:len(*digests)-1]
			},
		},
		{
			name: "inconsistent row sizes within a pack",
			deform: func(proof *OpeningProof, _ *[]kzg.Digest, _ *[][]fr.Element) {
				proof.ClaimedValues[0][1] = proof.ClaimedValues[0][1][:len(proof.ClaimedValues[0][1])-1]
			},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			proof := cloneProof()
			points := clonePoints()
			ds := append([]kzg.Digest{}, digests...)
			tc.deform(&proof, &ds, &points)

			// must return an error, and in particular must not panic
			err := BatchVerify(proof, ds, points, sha256.New(), testSrs.Vk)
			require.Error(t, err)
		})
	}
}

func TestCommit(t *testing.T) {

	assert := require.New(t)

	// sample polynomials
	nbPolys := 2
	p := make([][]fr.Element, nbPolys)
	for i := range nbPolys {
		p[i] = make([]fr.Element, i+10)
		for j := range i + 10 {
			p[i][j].MustSetRandom()
		}
	}

	// fflonk commit to them
	var x fr.Element
	x.MustSetRandom()
	proof, err := kzg.Open(Fold(p), x, testSrs.Pk)
	assert.NoError(err)

	// check that Open(C, x) = ∑_{i<t}Pᵢ(xᵗ)xⁱ
	var xt fr.Element
	var expo big.Int
	expo.SetUint64(uint64(nbPolys))
	xt.Exp(x, &expo)
	px := make([]fr.Element, nbPolys)
	for i := range nbPolys {
		px[i] = eval(p[i], xt)
	}
	y := eval(px, x)
	assert.True(y.Equal(&proof.ClaimedValue))
}

func TestGetIthRootOne(t *testing.T) {
	assert := require.New(t)

	order := getNextDivisorRMinusOne(9)
	omega, err := getIthRootOne(order)
	assert.NoError(err)
	var orderBigInt big.Int
	orderBigInt.SetUint64(uint64(order))
	omega.Exp(omega, &orderBigInt)
	assert.True(omega.IsOne())
}
