// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package starkcurve

import (
	crand "crypto/rand"
	"fmt"
	"math/big"
	"math/rand/v2"
	"testing"

	"github.com/consensys/gnark-crypto/ecc/stark-curve/fp"

	"github.com/consensys/gnark-crypto/ecc/stark-curve/fr"

	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/prop"
)

func TestIsOnG1(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	if testing.Short() {
		parameters.MinSuccessfulTests = nbFuzzShort
	} else {
		parameters.MinSuccessfulTests = nbFuzz
	}

	properties := gopter.NewProperties(parameters)

	properties.Property("[STARK-CURVE] g1Gen (affine) should be on the curve", prop.ForAll(
		func(a fp.Element) bool {
			var op1, op2 G1Affine
			op1.FromJacobian(&g1Gen)
			op2.Set(&op1)
			op2.Y.Mul(&op2.Y, &a)
			return op1.IsOnCurve() && !op2.IsOnCurve()
		},
		GenFp(),
	))

	properties.Property("[STARK-CURVE] g1Gen (Jacobian) should be on the curve", prop.ForAll(
		func(a fp.Element) bool {
			var op1, op2, op3 G1Jac
			op1.Set(&g1Gen)
			op3.Set(&g1Gen)

			op2 = fuzzG1Jac(&g1Gen, a)
			op3.Y.Mul(&op3.Y, &a)
			return op1.IsOnCurve() && op2.IsOnCurve() && !op3.IsOnCurve()
		},
		GenFp(),
	))

	properties.Property("[STARK-CURVE] IsInSubGroup and MulBy subgroup order should be the same", prop.ForAll(
		func(a fp.Element) bool {
			var op1, op2 G1Jac
			op1 = fuzzG1Jac(&g1Gen, a)
			_r := fr.Modulus()
			op2.mulWindowed(&op1, _r)
			return op1.IsInSubGroup() && op2.Z.IsZero()
		},
		GenFp(),
	))

	properties.TestingRun(t, gopter.ConsoleReporter(false))
}

func TestIsInSubGroupBatchG1(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	if testing.Short() {
		parameters.MinSuccessfulTests = 1
	} else {
		parameters.MinSuccessfulTests = 100
	}

	properties := gopter.NewProperties(parameters)

	// number of points to test
	const nbSamples = 100

	properties.Property("[STARK-CURVE] IsInSubGroupBatchG1 test should pass with high probability", prop.ForAll(
		func(mixer fr.Element) bool {
			// mixer ensures that all the words of a frElement are set
			var sampleScalars [nbSamples]fr.Element

			for i := range uint64(nbSamples) {
				sampleScalars[i].SetUint64(i+1).
					Mul(&sampleScalars[i], &mixer)
			}

			// random points in G1
			result := BatchScalarMultiplicationG1(&g1GenAff, sampleScalars[:])

			return IsInSubGroupBatchG1(result)
		},
		GenFr(),
	))

	properties.TestingRun(t, gopter.ConsoleReporter(false))
}

func TestG1Conversions(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	if testing.Short() {
		parameters.MinSuccessfulTests = nbFuzzShort
	} else {
		parameters.MinSuccessfulTests = nbFuzz
	}

	properties := gopter.NewProperties(parameters)

	properties.Property("[STARK-CURVE] Affine representation should be independent of the Jacobian representative", prop.ForAll(
		func(a fp.Element) bool {
			g := fuzzG1Jac(&g1Gen, a)
			var op1 G1Affine
			op1.FromJacobian(&g)
			return op1.X.Equal(&g1Gen.X) && op1.Y.Equal(&g1Gen.Y)
		},
		GenFp(),
	))

	properties.Property("[STARK-CURVE] Affine representation should be independent of a Extended Jacobian representative", prop.ForAll(
		func(a fp.Element) bool {
			var g g1JacExtended
			g.X.Set(&g1Gen.X)
			g.Y.Set(&g1Gen.Y)
			g.ZZ.Set(&g1Gen.Z)
			g.ZZZ.Set(&g1Gen.Z)
			gfuzz := fuzzg1JacExtended(&g, a)

			var op1 G1Affine
			op1.fromJacExtended(&gfuzz)
			return op1.X.Equal(&g1Gen.X) && op1.Y.Equal(&g1Gen.Y)
		},
		GenFp(),
	))

	properties.Property("[STARK-CURVE] Jacobian representation should be the same as the affine representative", prop.ForAll(
		func(a fp.Element) bool {
			var g G1Jac
			var op1 G1Affine
			op1.X.Set(&g1Gen.X)
			op1.Y.Set(&g1Gen.Y)

			var one fp.Element
			one.SetOne()

			g.FromAffine(&op1)

			return g.X.Equal(&g1Gen.X) && g.Y.Equal(&g1Gen.Y) && g.Z.Equal(&one)
		},
		GenFp(),
	))

	properties.Property("[STARK-CURVE] Converting affine symbol for infinity to Jacobian should output correct infinity in Jacobian", prop.ForAll(
		func() bool {
			var g G1Affine
			g.X.SetZero()
			g.Y.SetZero()
			var op1 G1Jac
			op1.FromAffine(&g)
			var one, zero fp.Element
			one.SetOne()
			return op1.X.Equal(&one) && op1.Y.Equal(&one) && op1.Z.Equal(&zero)
		},
	))

	properties.Property("[STARK-CURVE] Converting infinity in extended Jacobian to affine should output infinity symbol in Affine", prop.ForAll(
		func() bool {
			var g G1Affine
			var op1 g1JacExtended
			var zero fp.Element
			op1.X.Set(&g1Gen.X)
			op1.Y.Set(&g1Gen.Y)
			g.fromJacExtended(&op1)
			return g.X.Equal(&zero) && g.Y.Equal(&zero)
		},
	))

	properties.Property("[STARK-CURVE] Converting infinity in extended Jacobian to Jacobian should output infinity in Jacobian", prop.ForAll(
		func() bool {
			var g G1Jac
			var op1 g1JacExtended
			var zero, one fp.Element
			one.SetOne()
			op1.X.Set(&g1Gen.X)
			op1.Y.Set(&g1Gen.Y)
			g.fromJacExtended(&op1)
			return g.X.Equal(&one) && g.Y.Equal(&one) && g.Z.Equal(&zero)
		},
	))

	properties.Property("[STARK-CURVE] [Jacobian] Two representatives of the same class should be equal", prop.ForAll(
		func(a, b fp.Element) bool {
			op1 := fuzzG1Jac(&g1Gen, a)
			op2 := fuzzG1Jac(&g1Gen, b)
			return op1.Equal(&op2)
		},
		GenFp(),
		GenFp(),
	))
	properties.Property("[STARK-CURVE] BatchJacobianToAffineG1 and FromJacobian should output the same result", prop.ForAll(
		func(a, b fp.Element) bool {
			g1 := fuzzG1Jac(&g1Gen, a)
			g2 := fuzzG1Jac(&g1Gen, b)
			var op1, op2 G1Affine
			op1.FromJacobian(&g1)
			op2.FromJacobian(&g2)
			baseTableAff := BatchJacobianToAffineG1([]G1Jac{g1, g2})
			return op1.Equal(&baseTableAff[0]) && op2.Equal(&baseTableAff[1])
		},
		GenFp(),
		GenFp(),
	))

	properties.TestingRun(t, gopter.ConsoleReporter(false))
}

func TestG1AffineOps(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	parameters.MinSuccessfulTests = 10

	properties := gopter.NewProperties(parameters)

	genScalar := GenFr()

	properties.Property("[STARK-CURVE] Add(P,-P) should return the point at infinity", prop.ForAll(
		func(s fr.Element) bool {
			var op1, op2 G1Affine
			var sInt big.Int
			g := g1GenAff
			s.BigInt(&sInt)
			op1.ScalarMultiplication(&g, &sInt)
			op2.Neg(&op1)

			op1.Add(&op1, &op2)
			return op1.IsInfinity()

		},
		GenFr(),
	))

	properties.Property("[STARK-CURVE] Add(P,0) and Add(0,P) should return P", prop.ForAll(
		func(s fr.Element) bool {
			var op1, op2 G1Affine
			var sInt big.Int
			g := g1GenAff
			s.BigInt(&sInt)
			op1.ScalarMultiplication(&g, &sInt)
			op2.SetInfinity()

			op1.Add(&op1, &op2)
			op2.Add(&op2, &op1)
			return op1.Equal(&op2)

		},
		GenFr(),
	))

	properties.Property("[STARK-CURVE] Add should call double when adding the same point", prop.ForAll(
		func(s fr.Element) bool {
			var op1, op2 G1Affine
			var sInt big.Int
			g := g1GenAff
			s.BigInt(&sInt)
			op1.ScalarMultiplication(&g, &sInt)

			op2.Double(&op1)
			op1.Add(&op1, &op1)
			return op1.Equal(&op2)

		},
		GenFr(),
	))

	properties.Property("[STARK-CURVE] Doubling a point of order 2 should return the point at infinity", prop.ForAll(
		func(a fp.Element) bool {
			// Any (x,0) has a vertical tangent, so Double must return O and
			// cannot evaluate the slope (3x²+a)/2y. This pins that guard over
			// arbitrary x, most of which are off-curve; the on-curve points of
			// order 2 are covered by TestG1Order2 on the
			// curves that have one.
			var op1, op2, op3 G1Affine
			op1.X.Set(&a)
			op1.Y.SetZero()

			op2.Double(&op1)
			op3.Add(&op1, &op1)
			return op2.IsInfinity() && op3.IsInfinity()

		},
		GenFp(),
	))

	properties.Property("[STARK-CURVE] [2]G = double(G) + G - G", prop.ForAll(
		func(s fr.Element) bool {
			var sInt big.Int
			g := g1GenAff
			s.BigInt(&sInt)
			g.ScalarMultiplication(&g, &sInt)
			var op1, op2 G1Affine
			op1.ScalarMultiplication(&g, big.NewInt(2))
			op2.Double(&g)
			op2.Add(&op2, &g)
			op2.Sub(&op2, &g)
			return op1.Equal(&op2)
		},
		GenFr(),
	))

	properties.Property("[STARK-CURVE] [-s]G = -[s]G", prop.ForAll(
		func(s fr.Element) bool {
			g := g1GenAff
			var gj G1Jac
			gj.FromAffine(&g)
			var nbs, bs big.Int
			s.BigInt(&bs)
			nbs.Neg(&bs)

			var res = true

			// mulGLV
			{
				var op1, op2 G1Affine
				op1.ScalarMultiplication(&g, &bs).Neg(&op1)
				op2.ScalarMultiplication(&g, &nbs)
				res = res && op1.Equal(&op2)
			}

			// mulWindowed
			{
				var op1, op2 G1Jac
				op1.mulWindowed(&gj, &bs).Neg(&op1)
				op2.mulWindowed(&gj, &nbs)
				res = res && op1.Equal(&op2)
			}

			return res
		},
		GenFr(),
	))

	properties.Property("[STARK-CURVE] [Jacobian] Add should call double when adding the same point", prop.ForAll(
		func(a, b fp.Element) bool {
			fop1 := fuzzG1Jac(&g1Gen, a)
			fop2 := fuzzG1Jac(&g1Gen, b)
			var op1, op2 G1Jac
			op1.Set(&fop1).AddAssign(&fop2)
			op2.Double(&fop2)
			return op1.Equal(&op2)
		},
		GenFp(),
		GenFp(),
	))

	properties.Property("[STARK-CURVE] [Jacobian] Adding the opposite of a point to itself should output inf", prop.ForAll(
		func(a, b fp.Element) bool {
			fop1 := fuzzG1Jac(&g1Gen, a)
			fop2 := fuzzG1Jac(&g1Gen, b)
			fop2.Neg(&fop2)
			fop1.AddAssign(&fop2)
			return fop1.Equal(&g1Infinity)
		},
		GenFp(),
		GenFp(),
	))

	properties.Property("[STARK-CURVE] [Jacobian] Adding the inf to a point should not modify the point", prop.ForAll(
		func(a fp.Element) bool {
			fop1 := fuzzG1Jac(&g1Gen, a)
			fop1.AddAssign(&g1Infinity)
			var op2 G1Jac
			op2.Set(&g1Infinity)
			op2.AddAssign(&g1Gen)
			return fop1.Equal(&g1Gen) && op2.Equal(&g1Gen)
		},
		GenFp(),
	))

	properties.Property("[STARK-CURVE] [Jacobian Extended] addMixed (-G) should equal subMixed(G)", prop.ForAll(
		func(a fp.Element) bool {
			fop1 := fuzzG1Jac(&g1Gen, a)
			var p1, p1Neg G1Affine
			p1.FromJacobian(&fop1)
			p1Neg = p1
			p1Neg.Y.Neg(&p1Neg.Y)
			var o1, o2 g1JacExtended
			o1.addMixed(&p1Neg)
			o2.subMixed(&p1)

			return o1.X.Equal(&o2.X) &&
				o1.Y.Equal(&o2.Y) &&
				o1.ZZ.Equal(&o2.ZZ) &&
				o1.ZZZ.Equal(&o2.ZZZ)
		},
		GenFp(),
	))

	properties.Property("[STARK-CURVE] [Jacobian Extended] doubleMixed (-G) should equal doubleNegMixed(G)", prop.ForAll(
		func(a fp.Element) bool {
			fop1 := fuzzG1Jac(&g1Gen, a)
			var p1, p1Neg G1Affine
			p1.FromJacobian(&fop1)
			p1Neg = p1
			p1Neg.Y.Neg(&p1Neg.Y)
			var o1, o2 g1JacExtended
			o1.doubleMixed(&p1Neg)
			o2.doubleNegMixed(&p1)

			return o1.X.Equal(&o2.X) &&
				o1.Y.Equal(&o2.Y) &&
				o1.ZZ.Equal(&o2.ZZ) &&
				o1.ZZZ.Equal(&o2.ZZZ)
		},
		GenFp(),
	))

	properties.Property("[STARK-CURVE] [Jacobian] Addmix the negation to itself should output 0", prop.ForAll(
		func(a fp.Element) bool {
			fop1 := fuzzG1Jac(&g1Gen, a)
			fop1.Neg(&fop1)
			var op2 G1Affine
			op2.FromJacobian(&g1Gen)
			fop1.AddMixed(&op2)
			return fop1.Equal(&g1Infinity)
		},
		GenFp(),
	))

	properties.Property("[STARK-CURVE] scalar multiplication (double and add) should depend only on the scalar mod r", prop.ForAll(
		func(s fr.Element) bool {

			r := fr.Modulus()
			var g G1Jac
			g.ScalarMultiplication(&g1Gen, r)

			var scalar, blindedScalar, rminusone big.Int
			var op1, op2, op3, gneg G1Jac
			rminusone.SetUint64(1).Sub(r, &rminusone)
			op3.mulWindowed(&g1Gen, &rminusone)
			gneg.Neg(&g1Gen)
			s.BigInt(&scalar)
			blindedScalar.Mul(&scalar, r).Add(&blindedScalar, &scalar)
			op1.mulWindowed(&g1Gen, &scalar)
			op2.mulWindowed(&g1Gen, &blindedScalar)

			return op1.Equal(&op2) && g.Equal(&g1Infinity) && !op1.Equal(&g1Infinity) && gneg.Equal(&op3)

		},
		genScalar,
	))

	properties.Property("[STARK-CURVE] JointScalarMultiplicationBase and ScalarMultiplication should output the same results", prop.ForAll(
		func(s1, s2 fr.Element) bool {

			var op1, op2, temp G1Jac

			op1.JointScalarMultiplicationBase(&g1GenAff, s1.BigInt(new(big.Int)), s2.BigInt(new(big.Int)))
			temp.ScalarMultiplication(&g1Gen, s2.BigInt(new(big.Int)))
			op2.ScalarMultiplication(&g1Gen, s1.BigInt(new(big.Int))).
				AddAssign(&temp)

			return op1.Equal(&op2)

		},
		genScalar,
		genScalar,
	))

	properties.TestingRun(t, gopter.ConsoleReporter(false))
}

// addG1AffineViaJacobian is the affine addition as it was implemented
// before the slope was computed directly: mmadd-2007-bl with a.Z=b.Z=1,
// followed by a conversion back to affine coordinates. It is kept here only as
// the reference side of TestG1AffineAgainstJacobian.
func addG1AffineViaJacobian(p, a, b *G1Affine) *G1Affine {
	var q G1Jac
	// a is infinity, return b
	if a.IsInfinity() {
		p.Set(b)
		return p
	}
	// b is infinity, return a
	if b.IsInfinity() {
		p.Set(a)
		return p
	}
	if a.X.Equal(&b.X) {
		// if b == a, we double instead
		if a.Y.Equal(&b.Y) {
			q.DoubleMixed(a)
			return p.FromJacobian(&q)
		} else {
			// if b == -a, we return 0
			return p.SetInfinity()
		}
	}
	var H, HH, I, J, r, V fp.Element
	H.Sub(&b.X, &a.X)
	HH.Square(&H)
	I.Double(&HH).Double(&I)
	J.Mul(&H, &I)
	r.Sub(&b.Y, &a.Y)
	r.Double(&r)
	V.Mul(&a.X, &I)
	q.X.Square(&r).
		Sub(&q.X, &J).
		Sub(&q.X, &V).
		Sub(&q.X, &V)
	q.Y.Sub(&V, &q.X).
		Mul(&q.Y, &r)
	J.Mul(&a.Y, &J).Double(&J)
	q.Y.Sub(&q.Y, &J)
	q.Z.Double(&H)

	return p.FromJacobian(&q)
}

// doubleG1AffineViaJacobian is the affine doubling as it was implemented
// before the tangent slope was computed directly: mdbl-2007-bl with a.Z=1,
// followed by a conversion back to affine coordinates. The vertical tangent
// needed no special case there, because it came out of the formula as Z₃=2y=0.
// The FromAffine call is dead, and is reproduced only so that the reference is
// the previous implementation verbatim. It is kept here only as the reference
// side of TestG1AffineAgainstJacobian.
func doubleG1AffineViaJacobian(p, a *G1Affine) *G1Affine {
	var q G1Jac
	q.FromAffine(a)
	q.DoubleMixed(a)
	p.FromJacobian(&q)
	return p
}

// TestG1AffineAgainstJacobian pins Add and Double against the Jacobian
// implementations they replaced. The two are compared on their coordinates
// rather than as curve points, so a divergence in how the point at infinity is
// encoded would fail as well.
//
// The domain covers the generic case, P+P, P+(-P), an operand at infinity on
// either side, y=0 (the vertical tangent, which the Jacobian doubling absorbed
// as Z₃=2y=0 and the affine slope has to special-case), points off the curve,
// and every way the destination can alias an operand.
func TestG1AffineAgainstJacobian(t *testing.T) {
	t.Parallel()

	checkAdd := func(name string, a, b *G1Affine) {
		t.Helper()
		var want G1Affine
		addG1AffineViaJacobian(&want, a, b)

		var got G1Affine
		got.Add(a, b)
		if !got.Equal(&want) {
			t.Fatalf("%s: Add(a,b) = %s, want %s", name, got.String(), want.String())
		}
		// the destination aliases the first operand
		got.Set(a)
		got.Add(&got, b)
		if !got.Equal(&want) {
			t.Fatalf("%s: Add(a,b) with p==a = %s, want %s", name, got.String(), want.String())
		}
		// the destination aliases the second operand
		got.Set(b)
		got.Add(a, &got)
		if !got.Equal(&want) {
			t.Fatalf("%s: Add(a,b) with p==b = %s, want %s", name, got.String(), want.String())
		}
		if a.Equal(b) {
			// the destination aliases both operands
			got.Set(a)
			got.Add(&got, &got)
			if !got.Equal(&want) {
				t.Fatalf("%s: Add(a,a) with p==a = %s, want %s", name, got.String(), want.String())
			}
		}
	}

	checkDouble := func(name string, a *G1Affine) {
		t.Helper()
		var want G1Affine
		doubleG1AffineViaJacobian(&want, a)

		var got G1Affine
		got.Double(a)
		if !got.Equal(&want) {
			t.Fatalf("%s: Double(a) = %s, want %s", name, got.String(), want.String())
		}
		// the destination aliases the operand
		got.Set(a)
		got.Double(&got)
		if !got.Equal(&want) {
			t.Fatalf("%s: Double(a) with p==a = %s, want %s", name, got.String(), want.String())
		}
	}

	// A randomized walk through the subgroup: [s]G, [s+t]G, [s+2t]G, and so on.
	// The multiples are built in Jacobian coordinates, so none of the inputs
	// comes out of the functions under test.
	nbSamples := 300
	var s, step fr.Element
	s.MustSetRandom()
	step.MustSetRandom()

	var acc, stride G1Jac
	acc.ScalarMultiplication(&g1Gen, s.BigInt(new(big.Int)))
	stride.ScalarMultiplication(&g1Gen, step.BigInt(new(big.Int)))

	pts := make([]G1Affine, nbSamples)
	for i := range pts {
		pts[i].FromJacobian(&acc)
		acc.AddAssign(&stride)
	}

	for i := range pts {
		// pairing i with its mirror makes the middle sample of an odd-sized
		// walk land on the doubling branch of Add
		checkAdd(fmt.Sprintf("pair %d", i), &pts[i], &pts[nbSamples-1-i])
		checkDouble(fmt.Sprintf("point %d", i), &pts[i])
	}

	var inf, negP, yZero, offCurve G1Affine
	inf.SetInfinity()
	negP.Neg(&pts[0])
	// (x,0) for a random x: the vertical tangent. It is off the curve for
	// almost every x, but neither implementation checks, so the comparison
	// stays exact.
	yZero.X.MustSetRandom()
	yZero.Y.SetZero()
	offCurve.X.MustSetRandom()
	offCurve.Y.MustSetRandom()

	for _, tc := range []struct {
		name string
		a, b *G1Affine
	}{
		{"P+P", &pts[0], &pts[0]},
		{"P+(-P)", &pts[0], &negP},
		{"O+P", &inf, &pts[0]},
		{"P+O", &pts[0], &inf},
		{"O+O", &inf, &inf},
		{"(x,0)+(x,0)", &yZero, &yZero},
		{"(x,0)+P", &yZero, &pts[0]},
		{"P+(x,0)", &pts[0], &yZero},
		{"(x,0)+O", &yZero, &inf},
		{"offCurve+P", &offCurve, &pts[0]},
		{"offCurve+offCurve", &offCurve, &offCurve},
	} {
		checkAdd(tc.name, tc.a, tc.b)
	}

	for _, tc := range []struct {
		name string
		a    *G1Affine
	}{
		{"[2]O", &inf},
		{"[2](x,0)", &yZero},
		{"[2]offCurve", &offCurve},
	} {
		checkDouble(tc.name, tc.a)
	}
}

func TestG1BatchScalarMultiplication(t *testing.T) {

	parameters := gopter.DefaultTestParameters()
	if testing.Short() {
		parameters.MinSuccessfulTests = nbFuzzShort
	} else {
		parameters.MinSuccessfulTests = nbFuzzShort
	}

	properties := gopter.NewProperties(parameters)

	genScalar := GenFr()

	// size of the multiExps
	const nbSamples = 10

	properties.Property("[STARK-CURVE] BatchScalarMultiplication should be consistent with individual scalar multiplications", prop.ForAll(
		func(mixer fr.Element) bool {
			// mixer ensures that all the words of a fpElement are set
			var sampleScalars [nbSamples]fr.Element

			for i := 1; i <= nbSamples; i++ {
				sampleScalars[i-1].SetUint64(uint64(i)).
					Mul(&sampleScalars[i-1], &mixer)
			}

			result := BatchScalarMultiplicationG1(&g1GenAff, sampleScalars[:])

			if len(result) != len(sampleScalars) {
				return false
			}

			for i := range len(result) {
				var expectedJac G1Jac
				var expected G1Affine
				var b big.Int
				expectedJac.ScalarMultiplication(&g1Gen, sampleScalars[i].BigInt(&b))
				expected.FromJacobian(&expectedJac)
				if !result[i].Equal(&expected) {
					return false
				}
			}
			return true
		},
		genScalar,
	))

	properties.TestingRun(t, gopter.ConsoleReporter(false))
}

func TestG1JacTriple(t *testing.T) {
	// test triple on the generator and the infinity point
	// against double and add
	var a G1Jac
	a.Set(&g1Gen)
	var infinity G1Jac
	infinity.Set(&g1Infinity)

	var pTriple, pDoubleAdd G1Jac
	pTriple.Triple(&a)
	pDoubleAdd.Double(&a).AddAssign(&a)

	if !pTriple.Equal(&pDoubleAdd) {
		t.Fatalf("triple and double+add do not match: %s != %s", pTriple.String(), pDoubleAdd.String())
	}

	// same thing with infinity point
	pTriple.Triple(&infinity)
	pDoubleAdd.Double(&infinity).AddAssign(&infinity)

	if !pTriple.Equal(&pDoubleAdd) {
		t.Fatalf("triple and double+add do not match: %s != %s", pTriple.String(), pDoubleAdd.String())
	}
}

func BenchmarkG1JacTriple(b *testing.B) {
	var a G1Jac
	a.Set(&g1Gen)
	b.ResetTimer()
	for range b.N {
		a.Triple(&a)
	}
}

// ------------------------------------------------------------
// benches

func BenchmarkG1JacIsInSubGroup(b *testing.B) {
	var a G1Jac
	a.Set(&g1Gen)
	b.ResetTimer()
	for range b.N {
		a.IsInSubGroup()
	}

}

func BenchmarkG1JacEqual(b *testing.B) {
	var scalar fp.Element
	scalar.MustSetRandom()

	var a G1Jac
	a.ScalarMultiplication(&g1Gen, big.NewInt(42))

	b.Run("equal", func(b *testing.B) {
		var scalarSquared fp.Element
		scalarSquared.Square(&scalar)

		aZScaled := a
		aZScaled.X.Mul(&aZScaled.X, &scalarSquared)
		aZScaled.Y.Mul(&aZScaled.Y, &scalarSquared).Mul(&aZScaled.Y, &scalar)
		aZScaled.Z.Mul(&aZScaled.Z, &scalar)

		// Check the setup.
		if !a.Equal(&aZScaled) {
			b.Fatalf("invalid test setup")
		}

		b.ResetTimer()
		for range b.N {
			a.Equal(&aZScaled)
		}
	})

	b.Run("not equal", func(b *testing.B) {
		var aPlus1 G1Jac
		aPlus1.AddAssign(&g1Gen)

		// Check the setup.
		if a.Equal(&aPlus1) {
			b.Fatalf("invalid test setup")
		}

		b.ResetTimer()
		for range b.N {
			a.Equal(&aPlus1)
		}
	})
}

func BenchmarkBatchAddG1Affine(b *testing.B) {

	var P, R pG1AffineC16
	var RR ppG1AffineC16
	ridx := make([]int, len(P))

	// TODO P == R may produce skewed benches
	fillBenchBasesG1(P[:])
	fillBenchBasesG1(R[:])

	for i := range len(ridx) {
		ridx[i] = i
	}

	// random permute
	rand.Shuffle(len(ridx), func(i, j int) { ridx[i], ridx[j] = ridx[j], ridx[i] })

	for i, ri := range ridx {
		RR[i] = &R[ri]
	}

	b.ResetTimer()
	for range b.N {
		batchAddG1Affine[pG1AffineC16, ppG1AffineC16, cG1AffineC16](&RR, &P, len(P))
	}
}

func BenchmarkG1AffineBatchScalarMultiplication(b *testing.B) {
	// ensure every words of the scalars are filled
	var mixer fr.Element
	mixer.SetString("7716837800905789770901243404444209691916730933998574719964609384059111546487")

	const pow = 15
	const nbSamples = 1 << pow

	var sampleScalars [nbSamples]fr.Element

	for i := 1; i <= nbSamples; i++ {
		sampleScalars[i-1].SetUint64(uint64(i)).
			Mul(&sampleScalars[i-1], &mixer)
	}

	for i := 5; i <= pow; i++ {
		using := 1 << i

		b.Run(fmt.Sprintf("%d points", using), func(b *testing.B) {
			b.ResetTimer()
			for range b.N {
				_ = BatchScalarMultiplicationG1(&g1GenAff, sampleScalars[:using])
			}
		})
	}
}

func BenchmarkG1JacScalarMultiplication(b *testing.B) {
	for i := 0; i <= fr.Modulus().BitLen(); i += 8 {
		bound := new(big.Int).Lsh(big.NewInt(1), uint(i))
		scalar, err := crand.Int(crand.Reader, bound)
		if err != nil {
			b.Fatalf("failed to generate random scalar: %v", err)
		}

		var doubleAndAdd G1Jac
		b.Run(fmt.Sprintf("method=window/scalarwidth=%d", i), func(b *testing.B) {
			b.ResetTimer()
			for range b.N {
				doubleAndAdd.mulWindowed(&g1Gen, scalar)
			}
		})

	}
}

func BenchmarkG1JacScalarMultiplicationMethod(b *testing.B) {
	for i := 0; i <= fr.Modulus().BitLen(); i += 8 {
		bound := new(big.Int).Lsh(big.NewInt(1), uint(i))
		scalar, err := crand.Int(crand.Reader, bound)
		if err != nil {
			b.Fatalf("failed to generate random scalar: %v", err)
		}

		var res G1Jac
		b.Run(fmt.Sprintf("scalarwidth=%d", i), func(b *testing.B) {
			b.ResetTimer()
			for range b.N {
				res.ScalarMultiplication(&g1Gen, scalar)
			}
		})
	}
}

func BenchmarkG1JacAdd(b *testing.B) {
	var a G1Jac
	a.Double(&g1Gen)
	b.ResetTimer()
	for range b.N {
		a.AddAssign(&g1Gen)
	}
}

func BenchmarkG1JacAddMixed(b *testing.B) {
	var a G1Jac
	a.Double(&g1Gen)

	var c G1Affine
	c.FromJacobian(&g1Gen)
	b.ResetTimer()
	for range b.N {
		a.AddMixed(&c)
	}

}

func BenchmarkG1JacDouble(b *testing.B) {
	var a G1Jac
	a.Set(&g1Gen)
	b.ResetTimer()
	for range b.N {
		a.DoubleAssign()
	}

}

func BenchmarkG1JacExtAddMixed(b *testing.B) {
	var a g1JacExtended
	a.doubleMixed(&g1GenAff)

	var c G1Affine
	c.FromJacobian(&g1Gen)
	b.ResetTimer()
	for range b.N {
		a.addMixed(&c)
	}
}

func BenchmarkG1JacExtSubMixed(b *testing.B) {
	var a g1JacExtended
	a.doubleMixed(&g1GenAff)

	var c G1Affine
	c.FromJacobian(&g1Gen)
	b.ResetTimer()
	for range b.N {
		a.subMixed(&c)
	}
}

func BenchmarkG1JacExtDoubleMixed(b *testing.B) {
	var a g1JacExtended
	a.doubleMixed(&g1GenAff)

	var c G1Affine
	c.FromJacobian(&g1Gen)
	b.ResetTimer()
	for range b.N {
		a.doubleMixed(&c)
	}
}

func BenchmarkG1JacExtDoubleNegMixed(b *testing.B) {
	var a g1JacExtended
	a.doubleMixed(&g1GenAff)

	var c G1Affine
	c.FromJacobian(&g1Gen)
	b.ResetTimer()
	for range b.N {
		a.doubleNegMixed(&c)
	}
}

func BenchmarkG1JacExtAdd(b *testing.B) {
	var a, c g1JacExtended
	a.doubleMixed(&g1GenAff)
	c.double(&a)

	b.ResetTimer()
	for range b.N {
		a.add(&c)
	}
}

func BenchmarkG1JacExtDouble(b *testing.B) {
	var a g1JacExtended
	a.doubleMixed(&g1GenAff)

	b.ResetTimer()
	for range b.N {
		a.double(&a)
	}
}

func BenchmarkG1AffineAdd(b *testing.B) {
	var a G1Affine
	a.Double(&g1GenAff)
	b.ResetTimer()
	for range b.N {
		a.Add(&a, &g1GenAff)
	}
}

func BenchmarkG1AffineDouble(b *testing.B) {
	var a G1Affine
	a.Double(&g1GenAff)
	b.ResetTimer()
	for range b.N {
		a.Double(&a)
	}
}

func fuzzG1Jac(p *G1Jac, f fp.Element) G1Jac {
	var res G1Jac
	res.X.Mul(&p.X, &f).Mul(&res.X, &f)
	res.Y.Mul(&p.Y, &f).Mul(&res.Y, &f).Mul(&res.Y, &f)
	res.Z.Mul(&p.Z, &f)
	return res
}

func fuzzg1JacExtended(p *g1JacExtended, f fp.Element) g1JacExtended {
	var res g1JacExtended
	var ff, fff fp.Element
	ff.Square(&f)
	fff.Mul(&ff, &f)
	res.X.Mul(&p.X, &ff)
	res.Y.Mul(&p.Y, &fff)
	res.ZZ.Mul(&p.ZZ, &ff)
	res.ZZZ.Mul(&p.ZZZ, &fff)
	return res
}
