// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package poseidon2

import (
	"hash"
	"sync"

	fr "github.com/consensys/gnark-crypto/field/mamabear"
	gnarkHash "github.com/consensys/gnark-crypto/hash"
)

// NewMerkleDamgardHasher returns a Poseidon2 hasher using the Merkle-Damgard
// construction with the default parameters.
func NewMerkleDamgardHasher() gnarkHash.StateStorer {
	p := NewDefaultPermutation()
	return gnarkHash.NewMerkleDamgardHasher(
		p,
		make([]byte, p.params.Width/2*fr.Bytes),
	)
}

// NewDefaultPermutation returns a Poseidon2 permutation with the default
// recommended parameters for this field.
func NewDefaultPermutation() *Permutation {
	return &Permutation{params: GetDefaultParameters()}
}

// GetDefaultParameters returns a set of parameters for the Poseidon2 permutation.
// The default parameters are,
//
//  1. for compression:
//     - width: 16
//     - nbFullRounds: 6
//     - nbPartialRounds: 21
//
//  2. for sponge:
//     - width: 24
//     - nbFullRounds: 6
//     - nbPartialRounds: 21
var GetDefaultParameters = sync.OnceValue(func() *Parameters {
	return NewParameters(16, 6, 21)
})

var diag16 []fr.Element = make([]fr.Element, 16)
var diag24 []fr.Element = make([]fr.Element, 24)

func init() {
	// diagonal diag16 for the internal diagonal of the matrix of the compression layer
	// (from https://github.com/Plonky3/Plonky3 )
	diag16[0].SetUint64(562932773552127)
	diag16[1].SetUint64(1)
	diag16[2].SetUint64(2)
	diag16[3].SetUint64(281466386776065)
	diag16[4].SetUint64(3)
	diag16[5].SetUint64(4)
	diag16[6].SetUint64(281466386776064)
	diag16[7].SetUint64(562932773552126)
	diag16[8].SetUint64(562932773552125)
	diag16[9].SetUint64(560733817405441)
	diag16[10].SetUint64(492566176858113)
	diag16[11].SetUint64(562932739998721)
	diag16[12].SetUint64(2198956146688)
	diag16[13].SetUint64(70366596694016)
	diag16[14].SetUint64(35183298347008)
	diag16[15].SetUint64(33553408)

	// diagonal diag24 for the internal diagonal of the matrix of the sponge layer
	// (from https://github.com/Plonky3/Plonky3 )
	diag24[0].SetUint64(562932773552127)
	diag24[1].SetUint64(1)
	diag24[2].SetUint64(2)
	diag24[3].SetUint64(281466386776065)
	diag24[4].SetUint64(3)
	diag24[5].SetUint64(4)
	diag24[6].SetUint64(281466386776064)
	diag24[7].SetUint64(562932773552126)
	diag24[8].SetUint64(562932773552125)
	diag24[9].SetUint64(560733817405441)
	diag24[10].SetUint64(422199580164097)
	diag24[11].SetUint64(492566176858113)
	diag24[12].SetUint64(527749475205121)
	diag24[13].SetUint64(545341124378625)
	diag24[14].SetUint64(554136948965377)
	diag24[15].SetUint64(562932739998721)
	diag24[16].SetUint64(2198956146688)
	diag24[17].SetUint64(70366596694016)
	diag24[18].SetUint64(35183298347008)
	diag24[19].SetUint64(17591649173504)
	diag24[20].SetUint64(8795824586752)
	diag24[21].SetUint64(4397912293376)
	diag24[22].SetUint64(1099478073344)
	diag24[23].SetUint64(33553408)

	gnarkHash.RegisterHash(gnarkHash.POSEIDON2_MAMABEAR, func() hash.Hash {
		return NewMerkleDamgardHasher()
	})
}
