// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package poseidon2

import (
	"testing"

	fr "github.com/consensys/gnark-crypto/field/mamabear"
)

func TestMulMulInternalInPlaceWidth16(t *testing.T) {
	var input, expected [16]fr.Element
	for i := range input {
		input[i].MustSetRandom()
	}

	expected = input

	h := NewPermutation(16, 8, 32)
	h.matMulInternalInPlace(expected[:])

	var sum fr.Element
	sum.Set(&input[0])
	for i := 1; i < h.params.Width; i++ {
		sum.Add(&sum, &input[i])
	}
	for i := range h.params.Width {
		input[i].Mul(&input[i], &diag16[i]).
			Add(&input[i], &sum)
		if !input[i].Equal(&expected[i]) {
			t.Fatal("mat mul internal w/ diagonal doesn't match hand calculated")
		}
	}
}

func TestMulMulInternalInPlaceWidth24(t *testing.T) {
	var input, expected [24]fr.Element
	for i := range input {
		input[i].MustSetRandom()
	}

	expected = input

	h := NewPermutation(24, 8, 32)
	h.matMulInternalInPlace(expected[:])

	var sum fr.Element
	sum.Set(&input[0])
	for i := 1; i < h.params.Width; i++ {
		sum.Add(&sum, &input[i])
	}
	for i := range h.params.Width {
		input[i].Mul(&input[i], &diag24[i]).
			Add(&input[i], &sum)
		if !input[i].Equal(&expected[i]) {
			t.Fatal("mat mul internal w/ diagonal doesn't match hand calculated")
		}
	}
}

// denseMatrixMul returns m·x.
func denseMatrixMul(m [][]fr.Element, x []fr.Element) []fr.Element {
	res := make([]fr.Element, len(m))
	for i := range m {
		var tmp fr.Element
		for j := range m[i] {
			tmp.Mul(&m[i][j], &x[j])
			res[i].Add(&res[i], &tmp)
		}
	}
	return res
}

// TestDenseMatricesMatchInPlace checks that the dense matrices act on a random
// state as the in-place multiplications of the permutation.
func TestDenseMatricesMatchInPlace(t *testing.T) {
	for _, tc := range []struct {
		width, nbFullRounds, nbPartialRounds int
	}{
		{16, 6, 21},
		{24, 6, 21},
	} {
		h := NewPermutation(tc.width, tc.nbFullRounds, tc.nbPartialRounds)

		for name, step := range map[string]struct {
			dense   [][]fr.Element
			inPlace func([]fr.Element)
		}{
			"external": {h.params.ExternalMatrix(), h.matMulExternalInPlace},
			"internal": {h.params.InternalMatrix(), h.matMulInternalInPlace},
		} {
			x := make([]fr.Element, tc.width)
			for i := range x {
				x[i].MustSetRandom()
			}
			want := denseMatrixMul(step.dense, x)
			step.inPlace(x)
			for i := range x {
				if !x[i].Equal(&want[i]) {
					t.Fatalf("width %d, %s matrix: dense and in-place multiplications differ at index %d", tc.width, name, i)
				}
			}
		}
	}
}

func TestPoseidon2Width16(t *testing.T) {
	var input, expected [16]fr.Element
	// these are random values generated by MustSetRandom()
	input[0].SetUint64(2147483655)
	input[1].SetUint64(4294967303)
	input[2].SetUint64(6442450951)
	input[3].SetUint64(8589934599)
	input[4].SetUint64(10737418247)
	input[5].SetUint64(12884901895)
	input[6].SetUint64(15032385543)
	input[7].SetUint64(17179869191)
	input[8].SetUint64(19327352839)
	input[9].SetUint64(21474836487)
	input[10].SetUint64(23622320135)
	input[11].SetUint64(25769803783)
	input[12].SetUint64(27917287431)
	input[13].SetUint64(30064771079)
	input[14].SetUint64(32212254727)
	input[15].SetUint64(34359738375)

	expected[0].SetUint64(50602402429679)
	expected[1].SetUint64(205154033184305)
	expected[2].SetUint64(171690306064314)
	expected[3].SetUint64(290743356206654)
	expected[4].SetUint64(52057371620722)
	expected[5].SetUint64(357993730760812)
	expected[6].SetUint64(30792446669472)
	expected[7].SetUint64(560929088275684)
	expected[8].SetUint64(351129771614234)
	expected[9].SetUint64(167825709741404)
	expected[10].SetUint64(435628772411913)
	expected[11].SetUint64(263726494550579)
	expected[12].SetUint64(253184459815810)
	expected[13].SetUint64(470108995398990)
	expected[14].SetUint64(245845535172115)
	expected[15].SetUint64(339090281054048)

	h := NewPermutation(16, 8, 32)
	h.Permutation(input[:])
	for i := range h.params.Width {
		if !input[i].Equal(&expected[i]) {
			t.Fatal("mismatch error")
		}
	}
}

func TestPoseidon2Width24(t *testing.T) {
	var input, expected [24]fr.Element
	// these are random values generated by MustSetRandom()
	input[0].SetUint64(2147483655)
	input[1].SetUint64(4294967303)
	input[2].SetUint64(6442450951)
	input[3].SetUint64(8589934599)
	input[4].SetUint64(10737418247)
	input[5].SetUint64(12884901895)
	input[6].SetUint64(15032385543)
	input[7].SetUint64(17179869191)
	input[8].SetUint64(19327352839)
	input[9].SetUint64(21474836487)
	input[10].SetUint64(23622320135)
	input[11].SetUint64(25769803783)
	input[12].SetUint64(27917287431)
	input[13].SetUint64(30064771079)
	input[14].SetUint64(32212254727)
	input[15].SetUint64(34359738375)
	input[16].SetUint64(36507222023)
	input[17].SetUint64(38654705671)
	input[18].SetUint64(40802189319)
	input[19].SetUint64(42949672967)
	input[20].SetUint64(45097156615)
	input[21].SetUint64(47244640263)
	input[22].SetUint64(49392123911)
	input[23].SetUint64(51539607559)

	expected[0].SetUint64(221949310464874)
	expected[1].SetUint64(80986520567350)
	expected[2].SetUint64(188405925758112)
	expected[3].SetUint64(265381136928946)
	expected[4].SetUint64(531029040459252)
	expected[5].SetUint64(267299294930657)
	expected[6].SetUint64(232053702598666)
	expected[7].SetUint64(125866528816944)
	expected[8].SetUint64(375645824840808)
	expected[9].SetUint64(493982275312219)
	expected[10].SetUint64(491313642825887)
	expected[11].SetUint64(225430104088042)
	expected[12].SetUint64(12298241502257)
	expected[13].SetUint64(174077256549267)
	expected[14].SetUint64(211511214646258)
	expected[15].SetUint64(461473402745453)
	expected[16].SetUint64(373037057867494)
	expected[17].SetUint64(16199147773576)
	expected[18].SetUint64(527007590318455)
	expected[19].SetUint64(280256541869745)
	expected[20].SetUint64(457055166286236)
	expected[21].SetUint64(438914526671414)
	expected[22].SetUint64(454144458652198)
	expected[23].SetUint64(499223682805339)

	h := NewPermutation(24, 8, 32)
	h.Permutation(input[:])
	for i := range h.params.Width {
		if !input[i].Equal(&expected[i]) {
			t.Fatal("mismatch error")
		}
	}
}

func BenchmarkPoseidon2Width16(b *testing.B) {
	h := NewPermutation(16, 8, 32)

	var tmp [16]fr.Element
	for i := range tmp {
		tmp[i].MustSetRandom()
	}
	b.ResetTimer()
	for range b.N {
		h.Permutation(tmp[:])
	}
}

func BenchmarkPoseidon2Width24(b *testing.B) {
	h := NewPermutation(24, 8, 32)

	var tmp [24]fr.Element
	for i := range tmp {
		tmp[i].MustSetRandom()
	}
	b.ResetTimer()
	for range b.N {
		h.Permutation(tmp[:])
	}
}

// TestDefaultRoundNumbers pins the round numbers to the security analysis they
// come from, so they cannot be changed silently.
//
// Eq. (1) of the Poseidon2 paper (https://eprint.iacr.org/2023/323.pdf), for
// n = ceil(log2(p)) = 49, d = 3 and kappa = 128:
//
//	R_F = 8
//	R_P = ceil(1.075 * max(R_interp, R_GB))
//	R_interp = ceil(min{kappa,n}/log2(d)) + ceil(log_d(t)) - 5 = 29   (binding)
//	R_GB     = 25
//	       => R_P = ceil(1.075 * 29) = 32
//
// The bound scales with min{kappa, log2(p)}, so it is NOT safe to inherit these
// from a narrower field: koalabear saturates at n = 31 and needs only 20
// partial rounds, while mamabear needs 32.
func TestDefaultRoundNumbers(t *testing.T) {
	p := GetDefaultParameters()
	if p.Width != 16 {
		t.Fatalf("width: got %d, want 16", p.Width)
	}
	if p.NbFullRounds != 8 {
		t.Fatalf("full rounds: got %d, want 8", p.NbFullRounds)
	}
	if p.NbPartialRounds != 32 {
		t.Fatalf("partial rounds: got %d, want 32", p.NbPartialRounds)
	}
	if DegreeSBox() != 3 {
		t.Fatalf("sbox degree: got %d, want 3 (smallest d with gcd(d, p-1) = 1)", DegreeSBox())
	}
	if len(p.RoundKeys) != p.NbFullRounds+p.NbPartialRounds {
		t.Fatalf("round keys: got %d, want %d", len(p.RoundKeys), p.NbFullRounds+p.NbPartialRounds)
	}
}
