// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package mamabear

import "math/bits"

// MulBy3 x *= 3 (mod q)
func MulBy3(x *Element) {
	var y Element
	y.Double(x)
	x.Add(x, &y)
}

// MulBy5 x *= 5 (mod q)
func MulBy5(x *Element) {
	var y Element
	y.SetUint64(5)
	x.Mul(x, &y)
}

// MulBy13 x *= 13 (mod q)
func MulBy13(x *Element) {
	var y Element
	y.SetUint64(13)
	x.Mul(x, &y)
}

// Mul2ExpNegN multiplies x by 1/2^n
//
// Since the Montgomery constant is 2^52, the Montgomery form of 1/2^n is
// 2^{52-n}. Montgomery reduction works provided the input is
// < 2^52, so this works for 0 <= n <= 52.
//
// N.B. n must be <= 52.
func (z *Element) Mul2ExpNegN(x *Element, n uint32) *Element {
	r := montMul(x[0], uint64(1)<<(rBits-n))
	if r >= q {
		r -= q
	}
	z[0] = r
	return z
}

func fromMont(z *Element) {
	_fromMontGeneric(z)
}

func reduce(z *Element) {
	_reduceGeneric(z)
}

// Mul z = x * y (mod q)
//
// x and y must be less than q
func (z *Element) Mul(x, y *Element) *Element {
	// montMul is lazy: the result is in [0, 9q/8), one subtract short of
	// canonical.
	r := montMul(x[0], y[0])
	if r >= q {
		r -= q
	}
	z[0] = r
	return z
}

// Square z = x * x (mod q)
//
// x must be less than q
func (z *Element) Square(x *Element) *Element {
	// see Mul for algorithm documentation
	r := montMul(x[0], x[0])
	if r >= q {
		r -= q
	}
	z[0] = r
	return z
}

// Butterfly sets
//
//	a = a + b (mod q)
//	b = a - b (mod q)
func Butterfly(a, b *Element) {
	_butterflyGeneric(a, b)
}

// montMul computes a · b · R⁻¹ mod q where R = 2^52.
//
// The Montgomery radix is narrower than the word the element is stored in, so
// unlike the word-aligned case the shift by R is not free: the high half of the
// product has to be restitched across the 52-bit boundary, and the carry
// out of the low half has to be recovered explicitly.
//
//	t     ← ⌊a·b / R⌋                    (high bits of the product)
//	c₀    ← a·b mod R                    (low 52 bits)
//	m₀    ← c₀ · qInvNeg mod R
//	q'    ← ⌊m₀ · q / R⌋
//	carry ← 1 if c₀ > 0, else 0          (c₀ + m₀·q mod R is exactly 0 or R)
//	r     ← t + q' + carry
//
// For canonical inputs a, b ∈ [0, q) the result is in [0, 9q/8) ⊂ [0, 2q), so a
// single conditional subtract brings it back to [0, q). Callers that need a
// canonical value must do that subtract themselves.
func montMul(a, b uint64) uint64 {
	// Full product as hi:lo.
	hi, lo := bits.Mul64(a, b)

	// c₀ = a·b mod 2^52
	c0 := lo & rMask

	// t = ⌊a·b / 2^52⌋, restitched across the word boundary.
	t := (lo >> rBits) | (hi << (64 - rBits))

	// m₀ = c₀ · (-q⁻¹) mod 2^52
	m0 := (c0 * qInvNeg) & rMask

	// ⌊m₀ · q / 2^52⌋; the low 52 bits of m₀·q are (R − c₀) by
	// construction of m₀.
	mHi, mLo := bits.Mul64(m0, q)
	qVal := (mLo >> rBits) | (mHi << (64 - rBits))

	// carry = 1 when c₀ > 0: then c₀ + (m₀·q mod R) = R exactly and the addition
	// carries into bit 52. When c₀ = 0 so is m₀, and the sum is 0.
	carry := (c0 + (mLo & rMask)) >> rBits

	return t + qVal + carry
}
