// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package mamabear

// ExpBySqrtExp is equivalent to z.Exp(x, 3fff).
// It raises x to the (p-2^s-1)/2^(s+1) power using a shorter addition chain,
// where s the 2-adic valuation of p-1.
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpBySqrtExp(x Element) *Element {
	// addition chain:
	//
	//	_10       = 2*1
	//	_11       = 1 + _10
	//	_1100     = _11 << 2
	//	_1111     = _11 + _1100
	//	_11110000 = _1111 << 4
	//	_11111111 = _1111 + _11110000
	//	x12       = _11111111 << 4 + _1111
	//	return      x12 << 2 + _11
	//
	// Operations: 13 squares 5 multiplies
	var t0, t1 Element

	// Step 1: z = x^0x2
	z.Square(&x)

	// Step 2: z = x^0x3
	z.Mul(&x, z)

	// Step 4: t0 = x^0xc
	t0.Square(z)
	for s := 1; s < 2; s++ {
		t0.Square(&t0)
	}

	// Step 5: t0 = x^0xf
	t0.Mul(z, &t0)

	// Step 9: t1 = x^0xf0
	t1.Square(&t0)
	for s := 1; s < 4; s++ {
		t1.Square(&t1)
	}

	// Step 10: t1 = x^0xff
	t1.Mul(&t0, &t1)

	// Step 14: t1 = x^0xff0
	for range 4 {
		t1.Square(&t1)
	}

	// Step 15: t0 = x^0xfff
	t0.Mul(&t0, &t1)

	// Step 17: t0 = x^0x3ffc
	for range 2 {
		t0.Square(&t0)
	}

	// Step 18: z = x^0x3fff
	z.Mul(z, &t0)

	return z
}

// ExpByCbrt2q1o3 is equivalent to z.Exp(x, 15552aaaaaaab).
// It raises x to the (2q-1)/3 power using a shorter addition chain.
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpByCbrt2q1o3(x Element) *Element {
	// addition chain:
	//
	//	_10       = 2*1
	//	_100      = 2*_10
	//	_1000     = 2*_100
	//	_1010     = _10 + _1000
	//	_1010000  = _1010 << 3
	//	_1010100  = _100 + _1010000
	//	_10101000 = 2*_1010100
	//	_10101010 = _10 + _10101000
	//	i18       = _10101010 << 7 + _1010100
	//	i19       = 1 + i18
	//	i20       = i18 + i19
	//	return      (i20 << 16 + i19) << 17 + i20 + _10
	//
	// Operations: 47 squares 9 multiplies
	var t0, t1, t2 Element

	// Step 1: z = x^0x2
	z.Square(&x)

	// Step 2: t0 = x^0x4
	t0.Square(z)

	// Step 3: t1 = x^0x8
	t1.Square(&t0)

	// Step 4: t1 = x^0xa
	t1.Mul(z, &t1)

	// Step 7: t1 = x^0x50
	for range 3 {
		t1.Square(&t1)
	}

	// Step 8: t0 = x^0x54
	t0.Mul(&t0, &t1)

	// Step 9: t1 = x^0xa8
	t1.Square(&t0)

	// Step 10: t1 = x^0xaa
	t1.Mul(z, &t1)

	// Step 17: t1 = x^0x5500
	for range 7 {
		t1.Square(&t1)
	}

	// Step 18: t0 = x^0x5554
	t0.Mul(&t0, &t1)

	// Step 19: t1 = x^0x5555
	t1.Mul(&x, &t0)

	// Step 20: t0 = x^0xaaa9
	t0.Mul(&t0, &t1)

	// Step 36: t2 = x^0xaaa90000
	t2.Square(&t0)
	for s := 1; s < 16; s++ {
		t2.Square(&t2)
	}

	// Step 37: t1 = x^0xaaa95555
	t1.Mul(&t1, &t2)

	// Step 54: t1 = x^0x15552aaaa0000
	for range 17 {
		t1.Square(&t1)
	}

	// Step 55: t0 = x^0x15552aaaaaaa9
	t0.Mul(&t0, &t1)

	// Step 56: z = x^0x15552aaaaaaab
	z.Mul(z, &t0)

	return z
}
