// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

package mamabear

// Sqrt z = √x (mod p)
//
// Uses Tonelli-Shanks with p − 1 = 2^34 · Q, Q = 32767 (odd).
// If x is not a quadratic residue, Sqrt returns nil and leaves z unchanged.
func (z *Element) Sqrt(x *Element) *Element {
	// p ≡ 1 (mod 4), 2-adicity = 34, odd part Q = 32767 = 2^15 − 1.
	// Tonelli-Shanks:
	//   w = x^{(Q-1)/2}  → w = x^16383
	//   y = x · w        → y = x^{(Q+1)/2}
	//   b = w · y        → b = x^Q
	//   g = nonResidue^Q (precomputed, order 2^34)
	//   r = 34

	var y, b, t, w Element

	// w = x^16383 = x^{(Q-1)/2}
	w.expByLegendreExp(*x)

	y.Mul(x, &w)  // y = x^{(Q+1)/2}
	b.Mul(&w, &y) // b = x^Q

	// g = 3^Q mod p in Montgomery form (nonResidue^Q, order 2^34)
	var g = Element{393730615033094} // precomputed: 3^32767 mod p, in Montgomery form
	r := uint64(34)

	// Legendre check: t = b^{2^{r-1}} should be 1 for x to be a QR.
	t = b
	for i := uint64(0); i < r-1; i++ {
		t.Square(&t)
	}
	if t.IsZero() {
		return z.SetZero()
	}
	if !t.IsOne() {
		return nil
	}

	for {
		var m uint64
		t = b
		for !t.IsOne() {
			t.Square(&t)
			m++
		}
		if m == 0 {
			return z.Set(&y)
		}
		// t = g^{2^{r-m-1}}
		ge := int(r - m - 1)
		t = g
		for ge > 0 {
			t.Square(&t)
			ge--
		}
		g.Square(&t)
		y.Mul(&y, &t)
		b.Mul(&b, &g)
		r = m
	}
}

// expByLegendreExp computes z = x^16383 mod p  (= x^{(Q-1)/2} where Q = 32767).
//
// 16383 = 2^14 − 1.  Add chain: 13 sqrs + 5 muls = 18 ops.
func (z *Element) expByLegendreExp(x Element) *Element {
	var a2, a3, a4, a7, a14 Element

	// a2 = x^3 = x^{2^2-1}: x^2 * x
	a2.Square(&x)
	a2.Mul(&a2, &x)

	// a3 = x^7 = x^{2^3-1}: (x^3)^2 * x
	a3.Square(&a2)
	a3.Mul(&a3, &x)

	// a4 = x^15 = x^{2^4-1}: (x^7)^2 * x  [1 sqr + 1 mul, not 2+1]
	a4.Square(&a3)
	a4.Mul(&a4, &x)

	// a7 = x^127 = x^{2^7-1}: (x^15)^8 * x^7  [3 sqrs + 1 mul]
	a7 = a4
	for range 3 {
		a7.Square(&a7)
	}
	a7.Mul(&a7, &a3)

	// a14 = x^16383 = x^{2^14-1}: (x^127)^128 * x^127  [7 sqrs + 1 mul]
	a14 = a7
	for range 7 {
		a14.Square(&a14)
	}
	a14.Mul(&a14, &a7)

	z.Set(&a14)
	return z
}

// Cbrt z = ∛x (mod p)
//
// p ≡ 2 (mod 3), so every element has a unique cube root: z = x^{(2p−1)/3}.
func (z *Element) Cbrt(x *Element) *Element {
	var y Element
	y.expByCbrtExp(*x)
	return z.Set(&y)
}

// expByCbrtExp computes z = x^{(2p−1)/3} mod p  (= ∛x for p ≡ 2 mod 3).
//
// exp = 375288515701419 (hex 0x15552aaaaaaab).
// Addition chain generated by github.com/mmcloughlin/addchain v0.4.0:
//
//	_10       = 2*1
//	_100      = 2*_10
//	_1000     = 2*_100
//	_1010     = _10 + _1000
//	_1010000  = _1010 << 3
//	_1010100  = _100 + _1010000
//	_10101000 = 2*_1010100
//	_10101010 = _10 + _10101000
//	i18       = (_10101010 << 7) + _1010100
//	i19       = 1 + i18
//	i20       = i18 + i19
//	return    (i20 << 16 + i19) << 17 + i20 + _10
//
// Cost: 47 squarings + 9 multiplications = 56 operations.
func (z *Element) expByCbrtExp(x Element) *Element {
	var t0, t1, t2, t3, t4 Element

	t0.Square(&x)    // t0 = x^2          (_10)
	t1.Square(&t0)   // t1 = x^4          (_100)
	t2.Square(&t1)   // t2 = x^8          (_1000, temp)
	t3.Mul(&t0, &t2) // t3 = x^10         (_1010)
	t2.Square(&t3)   // 1st sqr of _1010 << 3
	t2.Square(&t2)
	t2.Square(&t2)   // t2 = x^80         (_1010000)
	t1.Mul(&t1, &t2) // t1 = x^84         (_1010100)
	t2.Square(&t1)   // t2 = x^168        (_10101000)
	t2.Mul(&t0, &t2) // t2 = x^170        (_10101010)
	for range 7 {
		t2.Square(&t2)
	} // t2 = x^21760
	t2.Mul(&t2, &t1) // t2 = x^21844      (i18)
	t4.Mul(&x, &t2)  // t4 = x^21845      (i19)
	t3.Mul(&t2, &t4) // t3 = x^43689      (i20)
	t2 = t3          // t2 = i20 (working copy; t3 keeps i20)
	for range 16 {
		t2.Square(&t2)
	} // t2 = x^{2863202304}  (i20 << 16)
	t2.Mul(&t2, &t4) // t2 = x^{2863224149}  (+ i19)
	for range 17 {
		t2.Square(&t2)
	} // t2 = x^{375288515657728} (<< 17)
	t2.Mul(&t2, &t3) // t2 = x^{375288515701417} (+ i20)
	z.Mul(&t2, &t0)  // z  = x^{375288515701419} (+ _10)
	return z
}
