// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

package mamabear

import "sync"

// Sqrt z = √x (mod p)
//
// if x is not a quadratic residue, Sqrt returns nil and leaves z unchanged.
func (z *Element) Sqrt(x *Element) *Element {
	return z.SqrtSarkar(x)
}

// SqrtTonelliShanks z = √x (mod p) using Tonelli-Shanks.
//
// p − 1 = 2^34 · Q, Q = 32767 (odd).  2-adicity = 34.
// If x is not a quadratic residue, SqrtTonelliShanks returns nil and leaves z unchanged.
func (z *Element) SqrtTonelliShanks(x *Element) *Element {
	var y, b, t, w Element

	// w = x^16383 = x^{(Q-1)/2}
	w.expByLegendreExp(*x)

	y.Mul(x, &w)  // y = x^{(Q+1)/2}
	b.Mul(&w, &y) // b = x^Q

	// g = 3^Q mod p, order 2^34
	var g = Element{393730615033094}
	r := uint64(34)

	// Legendre check: t = b^{2^{r-1}} = x^{(p-1)/2}; must be 1 for a QR.
	t = b
	for i := uint64(0); i < r-1; i++ {
		t.Square(&t)
	}
	if t.IsZero() {
		return z.SetZero()
	}
	if !t.IsOne() {
		return nil
	}

	for {
		var m uint64
		t = b
		for !t.IsOne() {
			t.Square(&t)
			m++
		}
		if m == 0 {
			return z.Set(&y)
		}
		ge := int(r - m - 1)
		t = g
		for ge > 0 {
			t.Square(&t)
			ge--
		}
		g.Square(&t)
		y.Mul(&y, &t)
		b.Mul(&b, &g)
		r = m
	}
}

// expByLegendreExp computes z = x^16383 mod p  (= x^{(Q-1)/2} where Q = 32767).
//
// 16383 = 2^14 − 1.  Add chain: 13 sqrs + 5 muls = 18 ops.
func (z *Element) expByLegendreExp(x Element) *Element {
	var a2, a3, a4, a7, a14 Element

	// a2 = x^3 = x^{2^2-1}: x^2 * x
	a2.Square(&x)
	a2.Mul(&a2, &x)

	// a3 = x^7 = x^{2^3-1}: (x^3)^2 * x
	a3.Square(&a2)
	a3.Mul(&a3, &x)

	// a4 = x^15 = x^{2^4-1}: (x^7)^2 * x  [1 sqr + 1 mul, not 2+1]
	a4.Square(&a3)
	a4.Mul(&a4, &x)

	// a7 = x^127 = x^{2^7-1}: (x^15)^8 * x^7  [3 sqrs + 1 mul]
	a7 = a4
	for range 3 {
		a7.Square(&a7)
	}
	a7.Mul(&a7, &a3)

	// a14 = x^16383 = x^{2^14-1}: (x^127)^128 * x^127  [7 sqrs + 1 mul]
	a14 = a7
	for range 7 {
		a14.Square(&a14)
	}
	a14.Mul(&a14, &a7)

	z.Set(&a14)
	return z
}

// Cbrt z = ∛x (mod p)
//
// p ≡ 2 (mod 3), so every element has a unique cube root: z = x^{(2p−1)/3}.
func (z *Element) Cbrt(x *Element) *Element {
	var y Element
	y.expByCbrtExp(*x)
	return z.Set(&y)
}

// expByCbrtExp computes z = x^{(2p−1)/3} mod p  (= ∛x for p ≡ 2 mod 3).
//
// exp = 375288515701419 (hex 0x15552aaaaaaab).
// Addition chain generated by github.com/mmcloughlin/addchain v0.4.0:
//
//	_10       = 2*1
//	_100      = 2*_10
//	_1000     = 2*_100
//	_1010     = _10 + _1000
//	_1010000  = _1010 << 3
//	_1010100  = _100 + _1010000
//	_10101000 = 2*_1010100
//	_10101010 = _10 + _10101000
//	i18       = (_10101010 << 7) + _1010100
//	i19       = 1 + i18
//	i20       = i18 + i19
//	return    (i20 << 16 + i19) << 17 + i20 + _10
//
// Cost: 47 squarings + 9 multiplications = 56 operations.
func (z *Element) expByCbrtExp(x Element) *Element {
	var t0, t1, t2, t3, t4 Element

	t0.Square(&x)    // t0 = x^2          (_10)
	t1.Square(&t0)   // t1 = x^4          (_100)
	t2.Square(&t1)   // t2 = x^8          (_1000, temp)
	t3.Mul(&t0, &t2) // t3 = x^10         (_1010)
	t2.Square(&t3)   // 1st sqr of _1010 << 3
	t2.Square(&t2)
	t2.Square(&t2)   // t2 = x^80         (_1010000)
	t1.Mul(&t1, &t2) // t1 = x^84         (_1010100)
	t2.Square(&t1)   // t2 = x^168        (_10101000)
	t2.Mul(&t0, &t2) // t2 = x^170        (_10101010)
	for range 7 {
		t2.Square(&t2)
	} // t2 = x^21760
	t2.Mul(&t2, &t1) // t2 = x^21844      (i18)
	t4.Mul(&x, &t2)  // t4 = x^21845      (i19)
	t3.Mul(&t2, &t4) // t3 = x^43689      (i20)
	t2 = t3          // t2 = i20 (working copy; t3 keeps i20)
	for range 16 {
		t2.Square(&t2)
	} // t2 = x^{2863202304}  (i20 << 16)
	t2.Mul(&t2, &t4) // t2 = x^{2863224149}  (+ i19)
	for range 17 {
		t2.Square(&t2)
	} // t2 = x^{375288515657728} (<< 17)
	t2.Mul(&t2, &t3) // t2 = x^{375288515701417} (+ i20)
	z.Mul(&t2, &t0)  // z  = x^{375288515701419} (+ _10)
	return z
}

// ---- Sarkar square root -------------------------------------------------------
//
// Implements the algorithm from:
//   "Computing Square Roots Faster than the Tonelli-Shanks/Adleman-Manders-Miller Algorithm"
// as used in gnark-crypto's bls12-377/fp package.
//
// p − 1 = 2^N · Q, N = sarkarN = 34, Q = 32767.
// The 2-torsion subgroup <g> has generator g = 3^Q, precomputed as sarkarG.
// The table sarkarGPow[i] = g^{2^i} is built once and cached.
//
// Total cost (amortising the one-time table build):
//   18 (expByLegendreExp) + 2 (xM) + 33 (Legendre sqrs) + 33 (xPow sqrs)
//   + ≤ K·L_max·2 ≈ 70 (chunk eval) ≈ 156 field ops = O(N) instead of O(N²).

const (
	sarkarN = 34
	sarkarK = 5
)

var sarkarL = [sarkarK]uint64{7, 7, 7, 6, 6} // sum = 33 = sarkarN - 1

// sarkarG = 3^32767 mod p, order 2^34 in F_p* (Montgomery form).
var sarkarG = Element{393730615033094}

var sarkarGPow [sarkarN]Element
var sarkarMinusOne Element
var initSarkarOnce sync.Once

func initSarkar() {
	sarkarGPow[0] = sarkarG
	for i := 1; i < sarkarN; i++ {
		sarkarGPow[i].Square(&sarkarGPow[i-1])
	}
	sarkarMinusOne.SetOne()
	sarkarMinusOne.Neg(&sarkarMinusOne)
}

// sarkarPowG sets z = g^exp (g = sarkarG, order 2^sarkarN).
func sarkarPowG(z *Element, exp uint64) *Element {
	if exp == 0 {
		return z.SetOne()
	}
	var acc Element
	acc.SetOne()
	for i := 0; exp > 0; i++ {
		if exp&1 == 1 {
			acc.Mul(&acc, &sarkarGPow[i])
		}
		exp >>= 1
	}
	return z.Set(&acc)
}

// sarkarFind returns the smallest i ≥ 0 such that delta^{2^i} = −1.
func sarkarFind(delta *Element) uint64 {
	var mu Element
	mu.Set(delta)
	var i uint64
	for !mu.Equal(&sarkarMinusOne) {
		mu.Square(&mu)
		i++
	}
	return i
}

// sarkarEval returns s such that alpha · g^s = 1.
func sarkarEval(alpha *Element) uint64 {
	var delta Element
	delta.Set(alpha)
	var s uint64
	for !delta.IsOne() {
		i := sarkarFind(&delta)
		s += uint64(1) << uint(sarkarN-1-int(i))
		if i > 0 {
			delta.Mul(&delta, &sarkarGPow[sarkarN-1-int(i)])
		} else {
			delta.Neg(&delta)
		}
	}
	return s
}

// SqrtSarkar z = √x (mod p) using Sarkar's algorithm.
//
// Runs in O(N) = O(34) field ops regardless of the input.
// If x is not a quadratic residue, SqrtSarkar returns nil and leaves z unchanged.
func (z *Element) SqrtSarkar(x *Element) *Element {
	if x.IsZero() {
		return z.SetZero()
	}

	initSarkarOnce.Do(initSarkar)

	// v = x^{(Q-1)/2} = x^16383
	var v Element
	v.expByLegendreExp(*x)

	// xM = x^Q = x · v^2
	var xM Element
	xM.Square(&v)
	xM.Mul(&xM, x)

	// Legendre check: xM^{2^{N-1}} must be 1 (else x is not a QR).
	t := xM
	for range sarkarN - 1 {
		t.Square(&t)
	}
	if t.IsZero() {
		return z.SetZero()
	}
	if !t.IsOne() {
		return nil
	}

	// Precompute xPow[i] = xM^{2^i} for i = 0 .. N-1.
	var xPow [sarkarN]Element
	xPow[0] = xM
	for i := 1; i < sarkarN; i++ {
		xPow[i].Square(&xPow[i-1])
	}

	// xis[k] = xM^{2^{N-1-Σ_{j≤k} L[j]}}  — one entry per chunk.
	var xis [sarkarK]Element
	var sumL uint64
	for i := range sarkarK {
		sumL += sarkarL[i]
		xis[i] = xPow[sarkarN-1-int(sumL)]
	}

	// Chunked discrete-log: find tt such that xM · g^{tt} = 1.
	var s, tt uint64
	for i := range sarkarK {
		tt = (s + tt) >> sarkarL[i]
		var gamma Element
		sarkarPowG(&gamma, tt)
		var alpha Element
		alpha.Mul(&xis[i], &gamma)
		s = sarkarEval(&alpha)
	}

	// sqrt(x) = x · v · g^{tt/2}  where tt = s + tt (final correction).
	tt = s + tt
	var gamma Element
	sarkarPowG(&gamma, tt>>1)
	z.Mul(x, &v)
	z.Mul(z, &gamma)
	return z
}
