// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package fft

import (
	"bytes"
	"reflect"
	"runtime"
	"testing"

	"github.com/consensys/gnark-crypto/ecc/bls12-381/fr"
	"github.com/stretchr/testify/require"
)

func TestDomainSerialization(t *testing.T) {

	domain := NewDomain(1 << 6)
	var reconstructed Domain

	var buf bytes.Buffer
	written, err := domain.WriteTo(&buf)
	if err != nil {
		t.Fatal(err)
	}
	var read int64
	read, err = reconstructed.ReadFrom(&buf)
	if err != nil {
		t.Fatal(err)
	}

	if written != read {
		t.Fatal("didn't read as many bytes as we wrote")
	}
	if !reflect.DeepEqual(domain, &reconstructed) {
		t.Fatal("Domain.SetBytes(Bytes()) failed")
	}
}

func TestDomainDeserializationInvalid(t *testing.T) {
	assert := require.New(t)

	valid := NewDomain(1 << 6)

	// serialize returns the encoding of d, with the fields of a valid domain
	// overwritten by tamper.
	serialize := func(tamper func(d *Domain)) []byte {
		d := *valid
		tamper(&d)
		var buf bytes.Buffer
		_, err := d.WriteTo(&buf)
		assert.NoError(err)
		return buf.Bytes()
	}

	one := fr.One()

	for _, tc := range []struct {
		name string
		data []byte
	}{
		{
			// bits.TrailingZeros64(0) is 64, which used to size the twiddle
			// allocations at 1<<63 and take the process down.
			name: "zero cardinality",
			data: serialize(func(d *Domain) { d.Cardinality = 0 }),
		}, {
			name: "cardinality not a power of 2",
			data: serialize(func(d *Domain) { d.Cardinality = (1 << 6) + 1 }),
		}, {
			// beyond the 2-adicity of every supported field
			name: "cardinality beyond 2-adicity",
			data: serialize(func(d *Domain) { d.Cardinality = 1 << 63 }),
		}, {
			name: "generator does not match cardinality",
			data: serialize(func(d *Domain) { d.Generator = one }),
		}, {
			name: "generator inverse mismatch",
			data: serialize(func(d *Domain) { d.GeneratorInv = one }),
		}, {
			name: "cardinality inverse mismatch",
			data: serialize(func(d *Domain) { d.CardinalityInv = one }),
		}, {
			name: "multiplicative generator inverse mismatch",
			data: serialize(func(d *Domain) { d.FrMultiplicativeGenInv = one }),
		}, {
			// a short read must not decode a zero-padded element
			name: "truncated element",
			data: serialize(func(d *Domain) {})[:8+fr.Bytes+fr.Bytes/2],
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			var d Domain
			_, err := d.ReadFrom(bytes.NewReader(tc.data))
			assert.Error(err, "invalid domain should be rejected")
		})
	}
}

func TestNewDomainCache(t *testing.T) {
	t.Run("CacheWithoutShift", func(t *testing.T) {
		key1 := domainCacheKey{
			m:   256,
			gen: GeneratorFullMultiplicativeGroup(),
		}
		require.Nil(t, getCachedDomain(key1), "cache should be empty initially")
		domain1 := NewDomain(256, WithCache())
		expected1 := NewDomain(256)
		require.Equal(t, domain1, expected1, "domain1 should equal expected1")
		require.Same(t, domain1, getCachedDomain(key1), "domain1 should be stored in cache")
	})

	t.Run("CacheWithShift", func(t *testing.T) {
		shift := fr.NewElement(5)
		key2 := domainCacheKey{
			m:   512,
			gen: shift,
		}
		require.Nil(t, getCachedDomain(key2), "cache should be empty initially")
		domain2 := NewDomain(512, WithShift(shift), WithCache())
		expected2 := NewDomain(512, WithShift(shift))
		require.Equal(t, domain2, expected2, "domain2 should equal expected2")
		require.Same(t, domain2, getCachedDomain(key2), "domain2 should be stored in cache")
	})
}

func TestGCBehavior(t *testing.T) {
	t.Run("DomainKeptAliveNotCollected", func(t *testing.T) {
		domain := NewDomain(1<<20, WithCache())
		require.NotNil(t, domain, "domain should not be empty")
		key := domainCacheKey{
			m:   1 << 20,
			gen: GeneratorFullMultiplicativeGroup(),
		}
		require.NotNil(t, getCachedDomain(key), "domain should be cached")
		runtime.GC()
		require.NotNil(t, getCachedDomain(key), "domain should still be cached")
		runtime.KeepAlive(domain)
	})

	t.Run("UnreferencedDomainCollected", func(t *testing.T) {
		domain := NewDomain(1<<19, WithCache())
		key := domainCacheKey{
			m:   1 << 19,
			gen: GeneratorFullMultiplicativeGroup(),
		}
		require.NotNil(t, getCachedDomain(key), "domain should be cached")
		// Last use of domain
		_ = domain.Cardinality
		runtime.GC()
		require.Nil(t, getCachedDomain(key), "unreferenced domain should be collected and removed from cache")
	})
}

func BenchmarkNewDomainCache(b *testing.B) {
	b.Run("WithCache", func(b *testing.B) {
		// lets first initialize in cache already
		cached := NewDomain(1<<20, WithCache())
		for b.Loop() {
			_ = NewDomain(1<<20, WithCache())
		}
		runtime.KeepAlive(cached) // prevent cached from being GCed
	})

	b.Run("WithoutCache", func(b *testing.B) {
		for b.Loop() {
			_ = NewDomain(1 << 20)
		}
	})
}

// Helper functions
func getCachedDomain(key domainCacheKey) *Domain {
	keyMapLock.Lock()
	keyLock, exists := domainGenLocks[key]
	if !exists {
		keyMapLock.Unlock()
		return nil
	}

	// Acquire key lock while holding global lock to prevent races
	keyLock.Lock()
	defer keyLock.Unlock()
	keyMapLock.Unlock()

	domainMapLock.Lock()
	defer domainMapLock.Unlock()
	if weak, exists := domainCache[key]; exists {
		return weak.Value()
	}
	return nil
}
