// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package polynomial

import (
	"math/bits"

	fr "github.com/consensys/gnark-crypto/field/koalabear"
	"github.com/consensys/gnark-crypto/field/koalabear/extensions"
	basepoly "github.com/consensys/gnark-crypto/field/koalabear/polynomial"
	"github.com/consensys/gnark-crypto/utils"
)

// MultiLinE6 tracks the values of a (dense i.e. not sparse) multilinear polynomial
// The variables are X₁ through Xₙ where n = log(len(.))
// .[∑ᵢ 2ⁱ⁻¹ bₙ₋ᵢ] = the polynomial evaluated at (b₁, b₂, ..., bₙ)
// It is understood that any hypercube evaluation can be extrapolated to a multilinear polynomial
type MultiLinE6 []extensions.E6

// Fold is partial evaluation function k[X₁, X₂, ..., Xₙ] → k[X₂, ..., Xₙ] by setting X₁=r
func (m *MultiLinE6) Fold(r extensions.E6) {
	mid := len(*m) / 2

	bottom, top := (*m)[:mid], (*m)[mid:]

	var t extensions.E6 // no need to update the top part

	// updating bookkeeping table
	// knowing that the polynomial f ∈ (k[X₂, ..., Xₙ])[X₁] is linear, we would get f(r) = f(0) + r(f(1) - f(0))
	// the following loop computes the evaluations of f(r) accordingly:
	//		f(r, b₂, ..., bₙ) = f(0, b₂, ..., bₙ) + r(f(1, b₂, ..., bₙ) - f(0, b₂, ..., bₙ))
	for i := range mid {
		// table[i] ← table[i] + r (table[i + mid] - table[i])
		t.Sub(&top[i], &bottom[i])
		t.Mul(&t, &r)
		bottom[i].Add(&bottom[i], &t)
	}

	*m = (*m)[:mid]
}

func (m *MultiLinE6) FoldParallel(r extensions.E6) utils.Task {
	mid := len(*m) / 2
	bottom, top := (*m)[:mid], (*m)[mid:]

	*m = bottom

	return func(start, end int) {
		var t extensions.E6 // no need to update the top part
		for i := start; i < end; i++ {
			// table[i] ← table[i]  + r (table[i + mid] - table[i])
			t.Sub(&top[i], &bottom[i])
			t.Mul(&t, &r)
			bottom[i].Add(&bottom[i], &t)
		}
	}
}

// FoldFromBase sets m to the partial evaluation X₁=r of the multilinear polynomial whose
// hypercube evaluations are the base field elements b:
//
//	m[i] = b[i] + r (b[i + len(b)/2] - b[i])
//
// m's backing array is reused if it is large enough.
func (m *MultiLinE6) FoldFromBase(b basepoly.MultiLin, r *extensions.E6) {
	mid := len(b) / 2
	m.resize(mid)
	m.foldFromBase(b, r, 0, mid)
}

// FoldFromBaseParallel is the parallel version of FoldFromBase. It sizes m, and returns
// a task that computes the entries m[start:end]. The task reads *r when it runs, so *r must
// not be modified until all tasks have completed.
func (m *MultiLinE6) FoldFromBaseParallel(b basepoly.MultiLin, r *extensions.E6) utils.Task {
	mid := len(b) / 2
	m.resize(mid)
	dst := *m

	return func(start, end int) {
		dst.foldFromBase(b, r, start, end)
	}
}

// EvaluateBase evaluates, on the given coordinates, the multilinear polynomial whose hypercube
// evaluations are the base field elements b. It first folds b into m by the first coordinate
// (see FoldFromBase), and then folds m by the remaining coordinates. m serves as scratch space,
// is overwritten, and its backing array is reused if it is large enough.
// Unlike Evaluate, no copy of the table is made, and b is left untouched.
func (m *MultiLinE6) EvaluateBase(b basepoly.MultiLin, coordinates []extensions.E6) extensions.E6 {
	if len(coordinates) == 0 {
		m.resize(1)
		return *(*m)[0].SetElement(&b[0])
	}

	m.FoldFromBase(b, &coordinates[0])
	for _, r := range coordinates[1:] {
		m.Fold(r)
	}
	return (*m)[0]
}

func (m *MultiLinE6) resize(n int) {
	if cap(*m) >= n {
		*m = (*m)[:n]
	} else {
		*m = make(MultiLinE6, n)
	}
}

func (m MultiLinE6) foldFromBase(b basepoly.MultiLin, r *extensions.E6, start, end int) {
	mid := len(b) / 2
	var diff fr.Element
	for i := start; i < end; i++ {
		diff.Sub(&b[mid+i], &b[i])
		m[i].MulByElement(r, &diff)
		m[i].AddElement(&m[i], &b[i])
	}
}

func (m MultiLinE6) Sum() extensions.E6 {
	s := m[0]
	for i := 1; i < len(m); i++ {
		s.Add(&s, &m[i])
	}
	return s
}

func _cloneE6(m MultiLinE6, p *PoolE6) MultiLinE6 {
	if p == nil {
		return m.Clone()
	} else {
		return p.Clone(m)
	}
}

func _dumpE6(m MultiLinE6, p *PoolE6) {
	if p != nil {
		p.Dump(m)
	}
}

// Evaluate extrapolate the value of the multilinear polynomial corresponding to m
// on the given coordinates
func (m MultiLinE6) Evaluate(coordinates []extensions.E6, p *PoolE6) extensions.E6 {
	// Folding is a mutating operation
	bkCopy := _cloneE6(m, p)

	// Evaluate step by step through repeated folding (i.e. evaluation at the first remaining variable)
	for _, r := range coordinates {
		bkCopy.Fold(r)
	}

	result := bkCopy[0]

	_dumpE6(bkCopy, p)
	return result
}

// Clone creates a deep copy of a bookkeeping table.
// Both multilinear interpolation and sumcheck require folding an underlying
// array, but folding changes the array. To do both one requires a deep copy
// of the bookkeeping table.
func (m MultiLinE6) Clone() MultiLinE6 {
	res := make(MultiLinE6, len(m))
	copy(res, m)
	return res
}

// Add two bookKeepingTables
func (m *MultiLinE6) Add(left, right MultiLinE6) {
	size := len(left)
	// Check that left and right have the same size
	if len(right) != size || len(*m) != size {
		panic("left, right and destination must have the right size")
	}

	// Add elementwise
	for i := range size {
		(*m)[i].Add(&left[i], &right[i])
	}
}

// EvalEqE6 computes Eq(q₁, ... , qₙ, h₁, ... , hₙ) = Π₁ⁿ Eq(qᵢ, hᵢ)
// where Eq(x,y) = xy + (1-x)(1-y) = 1 - x - y + xy + xy interpolates
//
//	    _________________
//	    |       |       |
//	    |   0   |   1   |
//	    |_______|_______|
//	y   |       |       |
//	    |   1   |   0   |
//	    |_______|_______|
//
//	            x
//
// In other words the polynomial evaluated here is the multilinear extrapolation of
// one that evaluates to q' == h' for vectors q', h' of binary values
func EvalEqE6(q, h []extensions.E6) extensions.E6 {
	var res, nxt, one, sum extensions.E6
	one.SetOne()
	for i := range len(q) {
		nxt.Mul(&q[i], &h[i]) // nxt <- qᵢ * hᵢ
		nxt.Double(&nxt)      // nxt <- 2 * qᵢ * hᵢ
		nxt.Add(&nxt, &one)   // nxt <- 1 + 2 * qᵢ * hᵢ
		sum.Add(&q[i], &h[i]) // sum <- qᵢ + hᵢ	TODO: Why not subtract one by one from nxt? More parallel?

		if i == 0 {
			res.Sub(&nxt, &sum) // nxt <- 1 + 2 * qᵢ * hᵢ - qᵢ - hᵢ
		} else {
			nxt.Sub(&nxt, &sum) // nxt <- 1 + 2 * qᵢ * hᵢ - qᵢ - hᵢ
			res.Mul(&res, &nxt) // res <- res * nxt
		}
	}
	return res
}

// Eq sets m to the representation of the polynomial Eq(q₁, ..., qₙ, *, ..., *) × m[0]
func (m *MultiLinE6) Eq(q []extensions.E6) {
	n := len(q)

	if len(*m) != 1<<n {
		panic("destination must have size 2 raised to the size of source")
	}

	//At the end of each iteration, m(h₁, ..., hₙ) = Eq(q₁, ..., qᵢ₊₁, h₁, ..., hᵢ₊₁)
	for i := range q { // In the comments we use a 1-based index so q[i] = qᵢ₊₁
		// go through all assignments of (b₁, ..., bᵢ) ∈ {0,1}ⁱ
		for j := range 1 << i {
			j0 := j << (n - i)                 // bᵢ₊₁ = 0
			j1 := j0 + 1<<(n-1-i)              // bᵢ₊₁ = 1
			(*m)[j1].Mul(&q[i], &(*m)[j0])     // Eq(q₁, ..., qᵢ₊₁, b₁, ..., bᵢ, 1) = Eq(q₁, ..., qᵢ, b₁, ..., bᵢ) Eq(qᵢ₊₁, 1) = Eq(q₁, ..., qᵢ, b₁, ..., bᵢ) qᵢ₊₁
			(*m)[j0].Sub(&(*m)[j0], &(*m)[j1]) // Eq(q₁, ..., qᵢ₊₁, b₁, ..., bᵢ, 0) = Eq(q₁, ..., qᵢ, b₁, ..., bᵢ) Eq(qᵢ₊₁, 0) = Eq(q₁, ..., qᵢ, b₁, ..., bᵢ) (1-qᵢ₊₁)
		}
	}
}

func (m MultiLinE6) NumVars() int {
	return bits.TrailingZeros(uint(len(m)))
}
