// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package polynomial

import (
	"testing"

	fr "github.com/consensys/gnark-crypto/field/koalabear"
	"github.com/consensys/gnark-crypto/field/koalabear/extensions"
	basepoly "github.com/consensys/gnark-crypto/field/koalabear/polynomial"
	"github.com/stretchr/testify/assert"
)

// TODO: Property based tests?
func TestFoldBilinearE6(t *testing.T) {

	for range 100 {

		// f = c₀ + c₁ X₁ + c₂ X₂ + c₃ X₁ X₂
		var coefficients [4]extensions.E6
		extensions.VectorE6(coefficients[:]).MustSetRandom()

		var r extensions.E6
		r.MustSetRandom()

		// interpolate at {0,1}²:
		m := make(MultiLinE6, 4)
		m[0] = coefficients[0]
		m[1].Add(&coefficients[0], &coefficients[2])
		m[2].Add(&coefficients[0], &coefficients[1])
		m[3].
			Add(&m[1], &coefficients[1]).
			Add(&m[3], &coefficients[3])

		m.Fold(r)

		// interpolate at {r}×{0,1}:
		var expected0, expected1 extensions.E6
		expected0.
			Mul(&r, &coefficients[1]).
			Add(&expected0, &coefficients[0])

		expected1.
			Mul(&r, &coefficients[3]).
			Add(&expected1, &coefficients[2]).
			Add(&expected0, &expected1)

		if !m[0].Equal(&expected0) || !m[1].Equal(&expected1) {
			t.Fail()
		}
	}
}

// TODO: Benchmark folding? Algorithms is pretty straightforward; unless we want to measure how well memory management is working

func TestFoldedEqTableE6(t *testing.T) {
	q := make([]extensions.E6, 2)
	q[0].SetInt64(2)
	q[1].SetInt64(3)

	m := make(MultiLinE6, 4)
	m[0].SetOne()
	m.Eq(q)

	eq := make([]extensions.E6, 4)
	p := make([]extensions.E6, 2)

	var one extensions.E6
	one.SetOne()

	for p0 := range 2 {
		p[1].SetZero()
		for p1 := range 2 {
			eq[p0*2+p1] = EvalEqE6(q, p)
			p[1].Add(&p[1], &one)
		}
		p[0].Add(&p[0], &one)
	}

	for i := range 4 {
		assert.Equal(t, eq[i], m[i], "folded table disagrees with EqEval", i)
	}

}

func TestFoldFromBaseE6(t *testing.T) {
	for _, n := range []int{2, 4, 8, 64} {
		b := make(basepoly.MultiLin, n)
		fr.Vector(b).MustSetRandom()
		var r extensions.E6
		r.MustSetRandom()

		// reference: lift b to the extension and fold in place
		lifted := make(MultiLinE6, n)
		for i := range b {
			lifted[i].SetElement(&b[i])
		}
		lifted.Fold(r)

		var got MultiLinE6
		got.FoldFromBase(b, &r)
		assert.Equal(t, lifted, got)

		// parallel version, split in two tasks, reusing a dirty destination
		par := make(MultiLinE6, n)
		task := par.FoldFromBaseParallel(b, &r)
		mid := n / 2
		task(0, mid/2)
		task(mid/2, mid)
		assert.Equal(t, lifted, par)
	}
}

func TestEvaluateBaseE6(t *testing.T) {
	for _, nbVars := range []int{0, 1, 2, 3, 6} {
		b := make(basepoly.MultiLin, 1<<nbVars)
		fr.Vector(b).MustSetRandom()
		coordinates := make([]extensions.E6, nbVars)
		extensions.VectorE6(coordinates).MustSetRandom()

		// reference: lift b to the extension and use Evaluate
		lifted := make(MultiLinE6, len(b))
		for i := range b {
			lifted[i].SetElement(&b[i])
		}
		want := lifted.Evaluate(coordinates, nil)

		var scratch MultiLinE6
		got := scratch.EvaluateBase(b, coordinates)
		assert.True(t, want.Equal(&got))

		// a dirty, larger scratch buffer gives the same result
		dirty := make(MultiLinE6, 2*len(b)+3)
		extensions.VectorE6(dirty).MustSetRandom()
		got = dirty.EvaluateBase(b, coordinates)
		assert.True(t, want.Equal(&got))
	}
}
