// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package polynomial

import (
	"github.com/consensys/gnark-crypto/field/koalabear/extensions"
	"github.com/consensys/gnark-crypto/utils"
)

// PoolE6 is a pool of slices of extensions.E6
type PoolE6 = utils.Pool[extensions.E6]

// NewPoolE6 returns a PoolE6 whose sub-pools hold slices of capacity up to each of maxN
func NewPoolE6(maxN ...int) PoolE6 {
	return utils.NewPool[extensions.E6](maxN...)
}
