// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package hash_to_curve

import (
	"testing"

	"github.com/consensys/gnark-crypto/ecc/bls12-381/fp"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/prop"
)

// GenFp generates an Fp element
func GenFp() gopter.Gen {
	return func(genParams *gopter.GenParameters) *gopter.GenResult {
		var elmt fp.Element
		elmt.MustSetRandom()

		return gopter.NewGenResult(elmt, gopter.NoShrinker)
	}
}

func TestG1SqrtRatio(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	if testing.Short() {
		parameters.MinSuccessfulTests = 10
	} else {
		parameters.MinSuccessfulTests = 100
	}

	properties := gopter.NewProperties(parameters)

	gen := GenFp()

	properties.Property("G1SqrtRatio must square back to the right value", prop.ForAll(
		func(u fp.Element, v fp.Element) bool {

			var seen fp.Element
			qr := G1SqrtRatio(&seen, &u, &v) == 0

			seen.
				Square(&seen).
				Mul(&seen, &v)

			var ref fp.Element
			if qr {
				ref = u
			} else {
				G1MulByZ(&ref, &u)
			}

			return seen.Equal(&ref)
		}, gen, gen))

	properties.TestingRun(t, gopter.ConsoleReporter(false))
}

// BenchmarkG1IsogenyPolynomials evaluates the four isogeny polynomials as
// G1Isogeny does (without the final batch inversion).
func BenchmarkG1IsogenyPolynomials(b *testing.B) {
	var x, y, xn, xd, yn, yd fp.Element
	x.MustSetRandom()
	y.MustSetRandom()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		g1IsogenyYDenominator(&yd, &x)
		g1IsogenyXDenominator(&xd, &x)
		g1IsogenyYNumerator(&yn, &x, &y)
		g1IsogenyXNumerator(&xn, &x)
	}
}

// BenchmarkG1IsogenyPolynomialsHorner evaluates the same polynomials with
// Horner's rule on the coefficient tables, for reference.
func BenchmarkG1IsogenyPolynomialsHorner(b *testing.B) {
	var x, y, xn, xd, yn, yd fp.Element
	x.MustSetRandom()
	y.MustSetRandom()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		g1EvalPolynomial(&yd, true, g1IsogenyYDenominatorMap, &x)
		g1EvalPolynomial(&xd, true, g1IsogenyXDenominatorMap, &x)
		g1EvalPolynomial(&yn, false, g1IsogenyYNumeratorMap, &x)
		yn.Mul(&yn, &y)
		g1EvalPolynomial(&xn, false, g1IsogenyXNumeratorMap, &x)
	}
}

// BenchmarkG1Isogeny measures the full isogeny map, batch inversion included.
func BenchmarkG1Isogeny(b *testing.B) {
	var x, y fp.Element
	x.MustSetRandom()
	y.MustSetRandom()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		G1Isogeny(&x, &y)
	}
}
