// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package hash_to_curve

import (
	"testing"

	"github.com/consensys/gnark-crypto/ecc/bw6-761/fp"
	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/prop"
)

func TestG2SqrtRatio(t *testing.T) {
	t.Parallel()
	parameters := gopter.DefaultTestParameters()
	if testing.Short() {
		parameters.MinSuccessfulTests = 10
	} else {
		parameters.MinSuccessfulTests = 100
	}

	properties := gopter.NewProperties(parameters)

	gen := GenFp()

	properties.Property("G2SqrtRatio must square back to the right value", prop.ForAll(
		func(u fp.Element, v fp.Element) bool {

			var seen fp.Element
			qr := G2SqrtRatio(&seen, &u, &v) == 0

			seen.
				Square(&seen).
				Mul(&seen, &v)

			var ref fp.Element
			if qr {
				ref = u
			} else {
				G2MulByZ(&ref, &u)
			}

			return seen.Equal(&ref)
		}, gen, gen))

	properties.TestingRun(t, gopter.ConsoleReporter(false))
}

// BenchmarkG2IsogenyPolynomials evaluates the four isogeny polynomials as
// G2Isogeny does (without the final batch inversion).
func BenchmarkG2IsogenyPolynomials(b *testing.B) {
	var x, y, xn, xd, yn, yd fp.Element
	x.MustSetRandom()
	y.MustSetRandom()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		g2IsogenyYDenominator(&yd, &x)
		g2IsogenyXDenominator(&xd, &x)
		g2IsogenyYNumerator(&yn, &x, &y)
		g2IsogenyXNumerator(&xn, &x)
	}
}

// BenchmarkG2IsogenyPolynomialsHorner evaluates the same polynomials with
// Horner's rule on the coefficient tables, for reference.
func BenchmarkG2IsogenyPolynomialsHorner(b *testing.B) {
	var x, y, xn, xd, yn, yd fp.Element
	x.MustSetRandom()
	y.MustSetRandom()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		g2EvalPolynomial(&yd, true, g2IsogenyYDenominatorMap, &x)
		g2EvalPolynomial(&xd, true, g2IsogenyXDenominatorMap, &x)
		g2EvalPolynomial(&yn, false, g2IsogenyYNumeratorMap, &x)
		yn.Mul(&yn, &y)
		g2EvalPolynomial(&xn, false, g2IsogenyXNumeratorMap, &x)
	}
}

// BenchmarkG2Isogeny measures the full isogeny map, batch inversion included.
func BenchmarkG2Isogeny(b *testing.B) {
	var x, y fp.Element
	x.MustSetRandom()
	y.MustSetRandom()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		G2Isogeny(&x, &y)
	}
}
