// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package polynomial

import (
	"sync"

	"github.com/consensys/gnark-crypto/field/mamabear/extensions"
)

// PolynomialE3 represented by coefficients in the field.
type PolynomialE3 []extensions.E3

// Degree returns the degree of the polynomial, which is the length of Data.
func (p *PolynomialE3) Degree() uint64 {
	return uint64(len(*p) - 1)
}

// Eval evaluates p at v
// returns a extensions.E3
func (p *PolynomialE3) Eval(v *extensions.E3) extensions.E3 {

	res := (*p)[len(*p)-1]
	for i := len(*p) - 2; i >= 0; i-- {
		res.Mul(&res, v)
		res.Add(&res, &(*p)[i])
	}

	return res
}

// Clone returns a copy of the polynomial
func (p *PolynomialE3) Clone() PolynomialE3 {
	_p := make(PolynomialE3, len(*p))
	copy(_p, *p)
	return _p
}

// Set to another polynomial
func (p *PolynomialE3) Set(p1 PolynomialE3) {
	if len(*p) != len(p1) {
		*p = p1.Clone()
		return
	}

	for i := range len(p1) {
		(*p)[i].Set(&p1[i])
	}
}

// AddConstantInPlace adds a constant to the polynomial, modifying p
func (p *PolynomialE3) AddConstantInPlace(c *extensions.E3) {
	for i := range len(*p) {
		(*p)[i].Add(&(*p)[i], c)
	}
}

// SubConstantInPlace subs a constant to the polynomial, modifying p
func (p *PolynomialE3) SubConstantInPlace(c *extensions.E3) {
	for i := range len(*p) {
		(*p)[i].Sub(&(*p)[i], c)
	}
}

// ScaleInPlace multiplies p by v, modifying p
func (p *PolynomialE3) ScaleInPlace(c *extensions.E3) {
	for i := range len(*p) {
		(*p)[i].Mul(&(*p)[i], c)
	}
}

// Scale multiplies p0 by v, storing the result in p
func (p *PolynomialE3) Scale(c *extensions.E3, p0 PolynomialE3) {
	if len(*p) != len(p0) {
		*p = make(PolynomialE3, len(p0))
	}
	for i := range len(p0) {
		(*p)[i].Mul(c, &p0[i])
	}
}

// Add adds p1 to p2
// This function allocates a new slice unless p == p1 or p == p2
func (p *PolynomialE3) Add(p1, p2 PolynomialE3) *PolynomialE3 {

	bigger := p1
	smaller := p2
	if len(bigger) < len(smaller) {
		bigger, smaller = smaller, bigger
	}

	if len(*p) == len(bigger) && (&(*p)[0] == &bigger[0]) {
		for i := range len(smaller) {
			(*p)[i].Add(&(*p)[i], &smaller[i])
		}
		return p
	}

	if len(*p) == len(smaller) && (&(*p)[0] == &smaller[0]) {
		for i := range len(smaller) {
			(*p)[i].Add(&(*p)[i], &bigger[i])
		}
		*p = append(*p, bigger[len(smaller):]...)
		return p
	}

	res := make(PolynomialE3, len(bigger))
	copy(res, bigger)
	for i := range len(smaller) {
		res[i].Add(&res[i], &smaller[i])
	}
	*p = res
	return p
}

// Sub subtracts p2 from p1
// TODO make interface more consistent with Add
func (p *PolynomialE3) Sub(p1, p2 PolynomialE3) *PolynomialE3 {
	if len(p1) != len(p2) || len(p2) != len(*p) {
		return nil
	}
	for i := range len(*p) {
		(*p)[i].Sub(&p1[i], &p2[i])
	}
	return p
}

// Equal checks equality between two polynomials
func (p *PolynomialE3) Equal(p1 PolynomialE3) bool {
	if (*p == nil) != (p1 == nil) {
		return false
	}

	if len(*p) != len(p1) {
		return false
	}

	for i := range p1 {
		if !(*p)[i].Equal(&p1[i]) {
			return false
		}
	}

	return true
}

func (p PolynomialE3) SetZero() {
	for i := range len(p) {
		p[i].SetZero()
	}
}

// InterpolateOnRangeE3 maps vector v to polynomial f
// such that f(i) = v[i] for 0 ≤ i < len(v).
// len(f) = len(v) and deg(f) ≤ len(v) - 1
func InterpolateOnRangeE3(v []extensions.E3) PolynomialE3 {
	nEvals := uint8(len(v))
	if int(nEvals) != len(v) {
		panic("interpolation method too inefficient for nEvals > 255")
	}
	lagrange := getLagrangeBasisE3(nEvals)

	var res PolynomialE3
	res.Scale(&v[0], lagrange[0])

	temp := make(PolynomialE3, nEvals)

	for i := uint8(1); i < nEvals; i++ {
		temp.Scale(&v[i], lagrange[i])
		res.Add(res, temp)
	}

	return res
}

// lagrange bases used by InterpolateOnRangeE3
var lagrangeBasisE3 sync.Map

func getLagrangeBasisE3(domainSize uint8) []PolynomialE3 {
	if res, ok := lagrangeBasisE3.Load(domainSize); ok {
		return res.([]PolynomialE3)
	}

	// not found. compute
	var res []PolynomialE3
	if domainSize >= 2 {
		res = computeLagrangeBasisE3(domainSize)
	} else if domainSize == 1 {
		res = []PolynomialE3{make(PolynomialE3, 1)}
		res[0][0].SetOne()
	}
	lagrangeBasisE3.Store(domainSize, res)

	return res
}

// computeLagrangeBasisE3 precomputes in explicit coefficient form for each 0 ≤ l < domainSize the polynomial
// pₗ := X (X-1) ... (X-l-1) (X-l+1) ... (X - domainSize + 1) / ( l (l-1) ... 2 (-1) ... (l - domainSize +1) )
// Note that pₗ(l) = 1 and pₗ(n) = 0 if 0 ≤ l < domainSize, n ≠ l
func computeLagrangeBasisE3(domainSize uint8) []PolynomialE3 {

	constTerms := make([]extensions.E3, domainSize)
	for i := range domainSize {
		constTerms[i].SetInt64(-int64(i))
	}

	res := make([]PolynomialE3, domainSize)
	multScratch := make(PolynomialE3, domainSize-1)

	// compute pₗ
	for l := range domainSize {

		// TODO @Tabaie Optimize this with some trees? O(log(domainSize)) polynomial mults instead of O(domainSize)? Then again it would be fewer big poly mults vs many small poly mults
		d := uint8(0) //d is the current degree of res
		for i := range domainSize {
			if i == l {
				continue
			}
			if d == 0 {
				res[l] = make(PolynomialE3, domainSize)
				res[l][domainSize-2] = constTerms[i]
				res[l][domainSize-1].SetOne()
			} else {
				current := res[l][domainSize-d-2:]
				timesConst := multScratch[domainSize-d-2:]

				timesConst.Scale(&constTerms[i], current[1:]) //TODO: Directly double and add since constTerms are tiny? (even less than 4 bits)
				nonLeading := current[0 : d+1]

				nonLeading.Add(nonLeading, timesConst)

			}
			d++
		}

	}

	// We have pₗ(i≠l)=0. Now scale so that pₗ(l)=1
	// Replace the constTerms with norms
	for l := range domainSize {
		constTerms[l].Neg(&constTerms[l])
		constTerms[l] = res[l].Eval(&constTerms[l])
	}
	constTerms = extensions.BatchInvertE3(constTerms)
	for l := range domainSize {
		res[l].ScaleInPlace(&constTerms[l])
	}

	return res
}
