// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package polynomial

import (
	"github.com/consensys/gnark-crypto/field/mamabear/extensions"
	"github.com/consensys/gnark-crypto/utils"
)

// PoolE3 is a pool of slices of extensions.E3
type PoolE3 = utils.Pool[extensions.E3]

// NewPoolE3 returns a PoolE3 whose sub-pools hold slices of capacity up to each of maxN
func NewPoolE3(maxN ...int) PoolE3 {
	return utils.NewPool[extensions.E3](maxN...)
}
