// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package polynomial

import (
	"encoding/json"
	"fmt"
	"runtime"
	"sort"
	"sync"
	"unsafe"

	"github.com/consensys/gnark-crypto/field/mamabear/extensions"
)

// Memory management for polynomials
// WARNING: This is not thread safe TODO: Make sure that is not a problem
// TODO: There is a lot of "unsafe" memory management here and needs to be vetted thoroughly

type sizedPoolE3 struct {
	maxN  int
	pool  sync.Pool
	stats poolStatsE3
}

type inUseDataE3 struct {
	allocatedFor []uintptr
	pool         *sizedPoolE3
}

type PoolE3 struct {
	//lock     sync.Mutex
	inUse    sync.Map
	subPools []sizedPoolE3
}

func (p *sizedPoolE3) get(n int) *extensions.E3 {
	p.stats.make(n)
	return p.pool.Get().(*extensions.E3)
}

func (p *sizedPoolE3) put(ptr *extensions.E3) {
	p.stats.dump()
	p.pool.Put(ptr)
}

func NewPoolE3(maxN ...int) (pool PoolE3) {

	sort.Ints(maxN)
	pool = PoolE3{
		subPools: make([]sizedPoolE3, len(maxN)),
	}

	for i := range pool.subPools {
		subPool := &pool.subPools[i]
		subPool.maxN = maxN[i]
		subPool.pool = sync.Pool{
			New: func() any {
				subPool.stats.Allocated++
				return getDataPointerE3(make([]extensions.E3, 0, subPool.maxN))
			},
		}
	}
	return
}

func (p *PoolE3) findCorrespondingPool(n int) *sizedPoolE3 {
	poolI := 0
	for poolI < len(p.subPools) && n > p.subPools[poolI].maxN {
		poolI++
	}
	return &p.subPools[poolI] // out of bounds error here would mean that n is too large
}

func (p *PoolE3) Make(n int) []extensions.E3 {
	pool := p.findCorrespondingPool(n)
	ptr := pool.get(n)
	p.addInUse(ptr, pool)
	return unsafe.Slice(ptr, n)
}

// Dump dumps a set of polynomials into the pool
func (p *PoolE3) Dump(slices ...[]extensions.E3) {
	for _, slice := range slices {
		ptr := getDataPointerE3(slice)
		if metadata, ok := p.inUse.Load(ptr); ok {
			p.inUse.Delete(ptr)
			metadata.(inUseDataE3).pool.put(ptr)
		} else {
			panic("attempting to dump a slice not created by the pool")
		}
	}
}

func (p *PoolE3) addInUse(ptr *extensions.E3, pool *sizedPoolE3) {
	pcs := make([]uintptr, 2)
	n := runtime.Callers(3, pcs)

	if prevPcs, ok := p.inUse.Load(ptr); ok { // TODO: remove if unnecessary for security
		panic(fmt.Errorf("re-allocated non-dumped slice, previously allocated at %v", runtime.CallersFrames(prevPcs.(inUseDataE3).allocatedFor)))
	}
	p.inUse.Store(ptr, inUseDataE3{
		allocatedFor: pcs[:n],
		pool:         pool,
	})
}

func printFrameE3(frame runtime.Frame) {
	fmt.Printf("\t%s line %d, function %s\n", frame.File, frame.Line, frame.Function)
}

func (p *PoolE3) printInUse() {
	fmt.Println("slices never dumped allocated at:")
	p.inUse.Range(func(_, pcs any) bool {
		fmt.Println("-------------------------")

		var frame runtime.Frame
		frames := runtime.CallersFrames(pcs.(inUseDataE3).allocatedFor)
		more := true
		for more {
			frame, more = frames.Next()
			printFrameE3(frame)
		}
		return true
	})
}

type poolStatsE3 struct {
	Used          int
	Allocated     int
	ReuseRate     float64
	InUse         int
	GreatestNUsed int
	SmallestNUsed int
}

type poolsStatsE3 struct {
	SubPools []poolStatsE3
	InUse    int
}

func (s *poolStatsE3) make(n int) {
	s.Used++
	s.InUse++
	if n > s.GreatestNUsed {
		s.GreatestNUsed = n
	}
	if s.SmallestNUsed == 0 || s.SmallestNUsed > n {
		s.SmallestNUsed = n
	}
}

func (s *poolStatsE3) dump() {
	s.InUse--
}

func (s *poolStatsE3) finalize() {
	s.ReuseRate = float64(s.Used) / float64(s.Allocated)
}

func getDataPointerE3(slice []extensions.E3) *extensions.E3 {
	return (*extensions.E3)(unsafe.SliceData(slice))
}

func (p *PoolE3) PrintPoolStats() {
	InUse := 0
	subStats := make([]poolStatsE3, len(p.subPools))
	for i := range p.subPools {
		subPool := &p.subPools[i]
		subPool.stats.finalize()
		subStats[i] = subPool.stats
		InUse += subPool.stats.InUse
	}

	stats := poolsStatsE3{
		SubPools: subStats,
		InUse:    InUse,
	}
	serialized, _ := json.MarshalIndent(stats, "", "  ")
	fmt.Println(string(serialized))
	p.printInUse()
}

func (p *PoolE3) Clone(slice []extensions.E3) []extensions.E3 {
	res := p.Make(len(slice))
	copy(res, slice)
	return res
}
